### ISSUE TITLE
rotate can't effective with size  under 241x241

### ISSUE THREAD

**Issue by zhoux2016** [libvips/libvips#1373] opened 2019-07-23 02:37 UTC
how can I rotate an image with  size 240x240
in my test
 vipsthumbnail  -s 240x240 -t img_5918.heic -o t5918-240x240t.jpg  it  wasn't rotated  
 vipsthumbnail  -s 241x241 -t img_5918.heic -o t5918-241x241t.jpg  it  was rotated
it can rotate with 240x or x240, but can't effective with 240x240, i need 240x240 effective

t5918-240x240t.jpg
![t5918-240x240t](https://user-images.githubusercontent.com/16449365/61678664-15609080-ad36-11e9-9639-34c1885d8511.jpg)

t5918-241x241t.jpg
![t5918-241x241t](https://user-images.githubusercontent.com/16449365/61678671-198cae00-ad36-11e9-92ed-d5904c15af50.jpg)

**Comment by jcupitt** [comment] 2019-07-23 08:34
Hello @zhoux2016,

It seems to work for me. For example:

```
john@kiwi:~/pics$ vipsheader -f orientation Example1.heic 
6
john@kiwi:~/pics$ vips copy Example1.heic x.jpg[strip]
john@kiwi:~/pics$ vipsthumbnail x.jpg
```

Makes this:

![tn_x](https://user-images.githubusercontent.com/580843/61695961-52c02080-ad2c-11e9-9814-5af1fef2b6ef.jpg)

So `Example1.heic` should look like that if auto-rotate fails.

Now I try:

```
john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 250 --rotate
```

To get:

![tn_Example1](https://user-images.githubusercontent.com/580843/61696059-8bf89080-ad2c-11e9-8244-d46b544e2a0d.jpg)

And

```
john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 240 --rotate
```

To get:

![tn_Example1](https://user-images.githubusercontent.com/580843/61696204-d974fd80-ad2c-11e9-8c22-a7e853fc37b5.jpg)

- What version of libvips are you using? I'm testing with 8.8.1. 
- Could it be a problem with the image you are using? Please upload your exact test image somewhere.

**Comment by zhoux2016** [comment] 2019-07-24 02:43
yesterday is  vips-8.8.0
today i updated  to vips-8.8.1
it turns out the same result

two sample image in the zip file

[exampleImg.zip](https://github.com/libvips/libvips/files/3424779/exampleImg.zip)

**Comment by zhoux2016** [comment] 2019-07-24 02:45
> Hello @zhoux2016,
> 
> It seems to work for me. For example:
> 
> ```
> john@kiwi:~/pics$ vipsheader -f orientation Example1.heic 
> 6
> john@kiwi:~/pics$ vips copy Example1.heic x.jpg[strip]
> john@kiwi:~/pics$ vipsthumbnail x.jpg
> ```
> 
> Makes this:
> 
> ![tn_x](https://user-images.githubusercontent.com/580843/61695961-52c02080-ad2c-11e9-9814-5af1fef2b6ef.jpg)
> 
> So `Example1.heic` should look like that if auto-rotate fails.
> 
> Now I try:
> 
> ```
> john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 250 --rotate
> ```
> 
> To get:
> 
> ![tn_Example1](https://user-images.githubusercontent.com/580843/61696059-8bf89080-ad2c-11e9-8244-d46b544e2a0d.jpg)
> 
> And
> 
> ```
> john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 240 --rotate
> ```
> 
> To get:
> 
> ![tn_Example1](https://user-images.githubusercontent.com/580843/61696204-d974fd80-ad2c-11e9-8c22-a7e853fc37b5.jpg)
> 
> * What version of libvips are you using? I'm testing with 8.8.1.
> * Could it be a problem with the image you are using? Please upload your exact test image somewhere.



> Hello @zhoux2016,
> 
> It seems to work for me. For example:
> 
> ```
> john@kiwi:~/pics$ vipsheader -f orientation Example1.heic 
> 6
> john@kiwi:~/pics$ vips copy Example1.heic x.jpg[strip]
> john@kiwi:~/pics$ vipsthumbnail x.jpg
> ```
> 
> Makes this:
> 
> ![tn_x](https://user-images.githubusercontent.com/580843/61695961-52c02080-ad2c-11e9-9814-5af1fef2b6ef.jpg)
> 
> So `Example1.heic` should look like that if auto-rotate fails.
> 
> Now I try:
> 
> ```
> john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 250 --rotate
> ```
> 
> To get:
> 
> ![tn_Example1](https://user-images.githubusercontent.com/580843/61696059-8bf89080-ad2c-11e9-8244-d46b544e2a0d.jpg)
> 
> And
> 
> ```
> john@kiwi:~/pics$ vipsthumbnail Example1.heic -s 240 --rotate
> ```
> 
> To get:
> 
> ![tn_Example1](https://user-images.githubusercontent.com/580843/61696204-d974fd80-ad2c-11e9-8c22-a7e853fc37b5.jpg)
> 
> * What version of libvips are you using? I'm testing with 8.8.1.
> * Could it be a problem with the image you are using? Please upload your exact test image somewhere.

yesterday is vips-8.8.0
today i updated to vips-8.8.1
it turns out the same result

two sample image in the zip file

[exampleImg.zip](https://github.com/libvips/libvips/files/3424795/exampleImg.zip)

**Comment by zhoux2016** [comment] 2019-07-24 03:23
yesterday is vips-8.8.0
today i updated to vips-8.8.1
it turns out the same result

sample image in the zip file
[IMG_6112.zip](https://github.com/libvips/libvips/files/3424883/IMG_6112.zip)

**Comment by jcupitt** [comment] 2019-07-24 09:40
Yes, I see it too with your test image:

```
john@kiwi:~/pics$ vipsthumbnail IMG_6112.HEIC -s 241 -o 241.jpg --rotate
john@kiwi:~/pics$ vipsthumbnail IMG_6112.HEIC -s 240 -o 240.jpg --rotate
```

240 rotates, but 241 does not.

I think it's a bug in libheif, I'll have a look.

**Comment by jcupitt** [comment] 2019-07-24 13:29
I tried with git master libheif and the problem is exactly reversed! 240 does not rotate, but 241 does.

**Comment by jcupitt** [comment] 2019-07-24 14:09
I found the problem: for small output sizes, libvips will attempt to use the thumbnail image inside the HEIC file as the source, rather than the main image. libheif seems to treat these two images differently in the way that rotation works. 

I'll open an issue on the libheif tracker. In the meantime, you can work around the problem for HEIC images by asing libheif to handle the rotation.

Instead of:

```
vipsthumbnail IMG_6112.HEIC -s 241 -o 241.jpg --rotate
```

Try

```
vipsthumbnail IMG_6112.HEIC[autorotate] -s 241 -o 241.jpg
```

and it should work for all image sizes.

**Comment by jcupitt** [comment] 2019-07-24 15:10
Ah found it, there was a libvips bug. 

It was fetching EXIF from the thumbnail, not from the main image, and obviously thumbnails don't have their own EXIF. Without EXIF, it was missing the orientation tag, and without that it could not auto-rotate correctly.

This fix will be in 8.8.2, thank you for the report!

In the meantime, using `[autorotate]` on HEIC files is a workaround.

**Comment by zhoux2016** [comment] 2019-07-25 00:51
> I found the problem: for small output sizes, libvips will attempt to use the thumbnail image inside the HEIC file as the source, rather than the main image. libheif seems to treat these two images differently in the way that rotation works.
> 
> I'll open an issue on the libheif tracker. In the meantime, you can work around the problem for HEIC images by asing libheif to handle the rotation.
> 
> Instead of:
> 
> ```
> vipsthumbnail IMG_6112.HEIC -s 241 -o 241.jpg --rotate
> ```
> 
> Try
> 
> ```
> vipsthumbnail IMG_6112.HEIC[autorotate] -s 241 -o 241.jpg
> ```
> 
> and it should work for all image sizes.

it works! thank you for the help. 
vipsthumbnail IMG_6112.HEIC[autorotate] -s 241 -o 241.jpg

**Comment by zhoux2016** [comment] 2019-07-25 00:53
> I found the problem: for small output sizes, libvips will attempt to use the thumbnail image inside the HEIC file as the source, rather than the main image. libheif seems to treat these two images differently in the way that rotation works.
> 
> I'll open an issue on the libheif tracker. In the meantime, you can work around the problem for HEIC images by asing libheif to handle the rotation.
> 
> Instead of:
> 
> ```
> vipsthumbnail IMG_6112.HEIC -s 241 -o 241.jpg --rotate
> ```
> 
> Try
> 
> ```
> vipsthumbnail IMG_6112.HEIC[autorotate] -s 241 -o 241.jpg
> ```
> 
> and it should work for all image sizes.

it works! thank you for the help.

**Comment by jcupitt** [comment] 2019-07-25 09:59
No problem, thanks for testing.

**Closed by jcupitt** 2019-07-25 09:59 UTC
Labels: bug, in development
