### ISSUE TITLE
Not able to disable auto rotate when using thumbnail_image

### ISSUE THREAD

**Issue by becoded** [libvips/libvips#1146] opened 2018-10-30 15:29 UTC
It seems that the flag auto-rotate for thumbnail_image doesn't have any effect when using vips command line.

Source file: https://github.com/ianare/exif-samples/blob/master/jpg/orientation/portrait_8.jpg

Using the following command:
`vips thumbnail_image portrait_8.jpg "portrait_8-600x450.jpg[strip,background=255 255 255,Q=95]" 600 --height=450 --auto-rotate=false`

As I specify to strip the metadata + don't do the auto-rotate, I would expect that my end result should be a rotated image but the images displays correctly.

> vips --version
> vips-8.7.0-Fri Aug 31 14:11:19 UTC 2018

**Comment by jcupitt** [comment] 2018-10-30 15:40
Hi @becoded,

You're right, I'd expect

```
vips thumbnail_image portrait_8.jpg x.jpg 128 --auto-rotate=false
```

to not rotate, but it does. I'll have a look.

`vipsthumbnail` seems to only rotate with `--rotate` option, so that works at least.

**Comment by jcupitt** [comment] 2018-10-31 09:46
It's because of the way that glib arg parsing works, sorry, I don't think this is directly fixable. 

The best workaround would be to use `vipsthumbnail` instead, ie. your example would be:

```
vipsthumbnail portrait_8.jpg -o portrait_8-600x450.jpg[strip,background=255,Q=95] -s 600x450
```

I think the best solution would be to tag the `auto-rotate` option as deprecated, and add a new one called `no-rotate` which defaults to FALSE. Your command-line would then be:

```
vips thumbnail_image portrait_8.jpg x.jpg 128 --no-auto-rotate
```

Background: glib command-line switches must take one of two forms:

1. `-v` or `--verbose`. A simple flag, meaning TRUE if present.
2. `-w 12` or `--width=12`. A switch with a single argument. The argument can be one of several types: string, int, filename etc.

You can't mix the two styles, so a no-arg flag can't have an `=arg` appended to it.

See https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html

**Comment by becoded** [comment] 2018-10-31 11:17
Hello @jcupitt 

I really appreciate it that you looked into this so fast!

I don't really see your point to be honest.
If I type just type `vips thumbnail_image`
I get 
```
...
   auto-rotate  - Use orientation tags to rotate image upright, input gboolean
			default: true
...
```
How I read this is as follows:
- auto-rotate is set to true if you don't define it in the options
- if you want to change it, it requires an boolean input.

So the only way to use the option auto-rotate is the 2nd form:
`--auto-rotate=true` or `--auto-rotate=false`

So it seems that auto-rotate is configured as a simple flag but should be changed to a switch with a single argument.

**Comment by jcupitt** [comment] 2018-10-31 11:23
I think the argument is:

* `thumbnail_image` has `auto-rotate` as an optional boolean argument. 
* All boolean arguments are mapped to simple GOption switches, with `--thing` meaning set `thing` TRUE
* However, `auto_rotate` is default TRUE, so you can never set it FALSE on the command-line.

It was an unfortunate oversight when `thumbnail_image` was designed.

Anyway, use `vipsthumbnail` instead for now and you should be OK.

**Comment by becoded** [comment] 2018-10-31 11:29
Will do.
Thanks again for the fast support!

**Comment by jcupitt** [comment] 2018-10-31 12:49
OK, fixed in git master. I'll close.

**Closed by jcupitt** 2018-10-31 12:49 UTC
Labels: bug, in development

**Comment by becoded** [comment] 2018-11-05 15:38
Hello @jcupitt 
I saw there was a new release with these changes included.
Is it expected that I don't see the new option if I do `vips thumbnail_image`
Also providing the new option gives me an error (Unknown option)

**Comment by jcupitt** [comment] 2018-11-05 15:46
Hello, there's 8.7.1, but that's just a bugfix from 8.7.0. 

This change will be in 8.8.0, due in the spring some time, or you can build from git master if you want it now.
