### ISSUE TITLE
Tiffsave and jpeg compression: pyramid issue

### ISSUE THREAD

**Issue by gil-c** [libvips/libvips#2313] opened 2021-06-22 14:06 UTC
Hello,

I use to call tiffsave to generate pyramidal ome.tiff files with the following arguments:
- pyramid=true
- tiled=true
- subifd=true
- page_height=..., in order to include the different channels ("toilet paper roll" method)
- bigtiff=true
- tile_width and tile_height=256
- xres and yres=...

This used to work fine also with all the available compression schemas (compression=..., Q=...).

In Libvips 8.11 there is the support for jp2k (which works nicely!) but now with jpeg the encoding seems corrupted for the lower resolutions of the pyramid. When I try to read them with tiffload and subifd (and then get any pixel value) I have the following error message:

`JPEGLib: Quantization table 0x00 was not defined`

This issue was not present in 8.10.

Gilles

**Comment by jcupitt** [comment] 2021-06-22 14:43
Hi @gil-c,

This is probably a libtiff / libjpeg bug. It has been fixed in libtiff:

https://gitlab.com/libtiff/libtiff/-/issues/266

But of course things haven't updated yet.

As a workaround, I would switch from libjpeg (I think you are probably using jpeg9d) to libjpeg-turbo.

**Comment by gil-c** [comment] 2021-06-23 07:16
Hi John,

The wired thing is that it works for the native resolution of the pyramid but not for the other resolutions.

I am using the official builds from the release page here: https://github.com/libvips/libvips/releases (vips-dev-w64-all).

Both libjpeg-62.dll files look identical for the 8.10 and 8.11 builds, and I thought that was already libjpeg-turbo. Is this correct?

**Comment by kleisauke** [comment] 2021-06-23 08:27
The https://github.com/libvips/build-win64-mxe binaries are built with MozJPEG. If you want, I could make a test release with merge request https://gitlab.com/libtiff/libtiff/-/merge_requests/257 backported.

**Comment by gil-c** [comment] 2021-06-23 11:49
Hi Kleis,

I am bit frustrated on my side with building libvips from sources. That would be a great step forward for me, but I still have to spend time to understand how to set up my environment. 

Also, I still don't understand John's point about the bug in libtiff / libjpeg. How was it working in 8.10 then?

Thanks both of you for your support

**Comment by gil-c** [comment] 2021-06-23 12:12
Ha sorry Kleis, now I am not sure to understand your proposition. For sure, if you build the 8.11 with the fix I would be happy to test it.

**Comment by kleisauke** [comment] 2021-06-23 15:25
I've backported those fixes with commit https://github.com/libvips/build-win64-mxe/commit/eea5381e5933074bdc335a7c6209c960fe5a5a95 on the [`tiff-backport`](https://github.com/libvips/build-win64-mxe/tree/tiff-backport) branch. The resulting 64-bit binaries can be found here:
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-all-8.11.0-tiff-backport.zip
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-web-8.11.0-tiff-backport.zip

Let me know if this works for you.

> Also, I still don't understand John's point about the bug in libtiff / libjpeg. How was it working in 8.10 then?

Did you test [v8.10.6](https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.6) from the `build-win64-mxe` repository? Since PR https://github.com/libvips/build-win64-mxe/pull/21 these MXE-binaries have switched from libjpeg-turbo to MozJPEG,  which could have triggered this bug in libtiff.

I think the binaries released on https://github.com/libvips/libvips/releases/tag/v8.10.6 were still built against libjpeg-turbo, so these were probably not affected by this bug.

**Comment by jcupitt** [comment] 2021-06-23 16:31
Yes, I think mozjpeg has a different issue: it enables progressive encoding by default (since progressive (or interlaced) jpegs are a little smaller), but libtiff does not allow progressively encoded tiles.

I believe one of the things that patch does is explicitly turn off progressive encoding.

**Comment by gil-c** [comment] 2021-06-23 16:31
Thanks a lot for the binaries. The problem remains..

here I made a minimal Python demo code:

```
import pyvips as vips

# generate an image
im1 = vips.Image.Black(2000, 2000) + 128
im1 = im1.copy(interpretation="b-w").cast("uint")
print("im1 : " + str(im1))
print("im1 average intensity : " + str(im1.avg()))

# save in tiff with compression, pyramid and subifds
# im1.tiffsave("tmp.tiff", compression="none", pyramid=True, subifd=True)  # working
# im1.tiffsave("tmp.tiff", compression="lzw", pyramid=True, subifd=True)  # working
# im1.tiffsave("tmp.tiff", compression="jp2k", pyramid=True, subifd=True)  # working
im1.tiffsave("tmp.tiff", compression="jpeg", pyramid=True, subifd=True)  # not working

# reload
im2 = vips.Image.new_from_file("tmp.tiff", subifd=0)  # subifd -1 is the native resolution, 0 is 1/2, etc.
print("im2 : " + str(im2))  # should be of shape 1000 x 1000 since we took the 1/2 resolution
print("im2 average intensity : " + str(im2.avg()))
```

Which crashes at the last line and says :
`pyvips.error.Error: unable to call avg
  JPEGLib: Quantization table 0x00 was not defined`


Note that while preparing this demo I also found that, in order to reproduce the issue, I have to restart my Python kernel (basically reload Libvips) when I switch from one compression method to another. Otherwise, running it once with let's say compression="none" and then again on the same kernel with "jpeg", then strangely it works.

**Comment by kleisauke** [comment] 2021-06-25 14:18
I could reproduce it on Windows with the above patched binaries. It seems to emit these warnings:
```
WARNING:pyvips:VIPS: mozjpeg library likely detected. Disable emission of Huffman tables in JpegTables tag, and use optimize_coding to avoid potential issues
```

By applying this patch:
```diff
--- a/reproducer.py
+++ b/reproducer.py
@@ -1,5 +1,8 @@
+import logging
 import pyvips as vips
 
+logging.basicConfig(level=logging.WARNING)
+
 # generate an image
 im1 = vips.Image.Black(2000, 2000) + 128
 im1 = im1.copy(interpretation="b-w").cast("uint")
```

Probably merge request https://gitlab.com/libtiff/libtiff/-/merge_requests/254 and issue https://github.com/mozilla/mozjpeg/issues/398 are related here.

**Comment by kleisauke** [comment] 2021-06-28 11:25
I've reported upstream that this issue is still present by commenting to [libtiff/libtiff#266](https://gitlab.com/libtiff/libtiff/-/issues/266).

**Comment by kleisauke** [comment] 2021-06-28 14:02
I was able to reproduce this with libtiff v4.3.0 built against libjpeg turbo v2.1.0, so it doesn't seem related to that issue nor to MozJPEG (I think). I also tried older versions of libtiff without success. Reproducer:
```bash
$ vips black x.v 2000 2000
$ vips copy x.v x.tif[compression=jpeg,pyramid,subifd]
$ vips copy x.tif[subifd=0] x2.jpg
```

Removing the the `compression=jpeg` parameter works. But when reloading the produced image it sometimes throws the `tiff2vips: subifd 0 out of range, only 0--X available` error.
```bash
$ vips black x.v 2000 2000
$ vips copy x.v x.tif[pyramid,subifd]
# sometimes throws `tiff2vips: subifd 0 out of range, only 0--X available` where X is a random number
$ vips copy x.tif[subifd=0] x2.jpg
tiff2vips: subifd 0 out of range, only 0--1753415677 available
```

**Comment by gil-c** [comment] 2021-06-28 15:02
`subifd 0 out of range` is misleading cause -1 should be valid from the api point of view. It is the default value and means "native resolution".

**Comment by jcupitt** [comment] 2021-06-28 15:08
Oh dear, this is bad, I'm sure it used to work. I'll have a look.

**Comment by jcupitt** [comment] 2021-06-28 15:14
I see it with libtiff 4.2 and libjpeg-turbo 2.0.6 as well (packages on ubuntu 21.04).

```
john@banana ~/pics $ vips copy k2.jpg x.tif[pyramid,subifd,compression=jpeg]
john@banana ~/pics $ vips copy x.tif[subifd=0] x.jpg

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 0 x 0

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 128 x 0

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 256 x 0

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 384 x 0

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 512 x 0

(vips:346315): VIPS-WARNING **: 16:13:23.230: error in tile 640 x 0
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
john@banana ~/pics $ 
```

**Comment by jcupitt** [comment] 2021-06-28 15:46
I found your second bug (we were passing int* when libtiff was expecting uint16*) but I've made no progress on the first :(

**Comment by kleisauke** [comment] 2021-06-28 17:00
I could not reproduce this with the https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.6 binaries. These were build against libtiff 4.2.0 and MozJPEG 4.0.3.

**Comment by jcupitt** [comment] 2021-06-28 17:39
I see it on Ubuntu 20.04 as well, which is libtiff 4.1 and libjpeg-turbo 2.0.3.

It fails in exactly the same way on ubuntu 18.04 (!!), which is libtiff 4.0.9 and libjpeg-turbo 1.5.2.

I suppose I tested the subifd stuff with jp2k and with no compression, but I must have forgotten to test jpeg compression :(

I'll take a closer look at those patches and see if they help.

**Comment by jcupitt** [comment] 2021-06-28 19:07
Actually, any jpeg pyramid fails:

```
$ vips copy k2.jpg x.tif[tile,pyramid,compression=jpeg]
$ vips copy x.tif[page=2] x.jpg

(vips:554087): VIPS-WARNING **: 20:03:27.019: error in tile 0 x 0

(vips:554087): VIPS-WARNING **: 20:03:27.019: error in tile 128 x 0

(vips:554087): VIPS-WARNING **: 20:03:27.019: error in tile 256 x 0
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
JPEGLib: Quantization table 0x00 was not defined
```

That's with the libtiff patches.  If I checkout 8.10 and build that, it's fine.

It must be a libvips bug, perhaps something that was introduced with the subifd work and not spotted by the test suite.

**Comment by jcupitt** [comment] 2021-06-28 19:25
Found it!

https://github.com/libvips/libvips/commit/95bf1367ba340125d0e3d9111fa97ddbcd880b8d

It should work now. It was my fault: I "optimised" pyramid layer copy, and broke it. I've added a test too.

**Comment by jcupitt** [comment] 2021-06-29 07:40
OK, let's push out 8.11.1 with this fix and a few others. Please open a new issue if that version is broken too (I hope not).

**Closed by jcupitt** 2021-06-29 07:40 UTC
Labels: bug

**Comment by gil-c** [comment] 2021-06-29 07:42
Thanks a lot!!
