### ISSUE TITLE
windows cli build libjpeg-turbo

### ISSUE THREAD

**Issue by flexphperia** [libvips/libvips#1637] opened 2020-05-03 09:33 UTC
I read that `libjpeg-turbo` improves libvids performance and wanted to try using windows.
From what I've read I have to build from libvids sources.
Is there a ready version of vipsthumbnail.exe and vips.exe using `libjpeg-turbo`?
I tried to build from sources on ubuntu through the `$ ./build.sh 8.9 web` command but it returns such an error to me.
```
Cloning into 'jhbuild'...
error: inflate: data stream error (invalid distance too far back)
fatal: pack has bad object at offset 22328447: inflate returned -3
fatal: index-pack failed
The command '/bin/sh -c git clone https://github.com/GNOME/jhbuild.git    && cd jhbuild    && git checkout -b stable $JHBUILD_REVISION    && ./autogen.sh --prefix=/usr/local    && make    && make install' returned a non-zero code: 128
```

I have no experience in linux, this was my first use on an Ubuntu via virtual machine. 
Can anyone build a version of windows with `libjpeg-turbo` for me? 
I just need JPG support (resizing via vipsthumbnail.exe and sharpen and autorot via vips.exe; as little dependencies as possible to work as fast as it can)

**Comment by jcupitt** [comment] 2020-05-03 10:23
Hello @flexphperia,

The official win32 binaries already use libjpeg-turbo. You can see the build instructions here:

https://github.com/libvips/build-win64/blob/master/8.9/vips.modules#L441

I don't know why the build failed for you. I tried just now and it seems to work here. Perhaps there was some hiccough somewhere. I would try again in a few hours.

`vipsthumbnail` does autorot for you now, this shouldn't be necessary. I also would not sharpen, but of course that's up to you.

**Comment by flexphperia** [comment] 2020-05-03 10:34
Ok thanks for the answer. I was not sure that it is using libjpeg-turbo because there is no such file `libjpeg-turbo.dll` in the file `vips-dev-w64-web-8.9.2.zip`, but I have no experience in this field so it may have fooled me.

Would you be so kind as to tell me how I can improve the speed of libvips CLI when resizing images?
By using `vipsthumbnail.exe` it obtains time about `260ms` for JPG 24mpx file on my machine.
Is it possible to speed up anything by building libvips from source or doing anything?
I need minimal functionality only JPG support (sharpening and autorot functionality).

I used binding in C# - NetVips to build my own NET Framework app but I got worse results than using CLI.

**Comment by jcupitt** [comment] 2020-05-03 11:03
The C# should be a little quicker, perhaps 50ms. What program were you benchmarking?

**Comment by flexphperia** [comment] 2020-05-03 11:09
My C# app was console app that takes as argument image path and saves to file:
```
Stopwatch sw = new Stopwatch();
sw.Start();
NetVips.Image vipsimg = Image.NewFromFile(inputPath, true);
vipsimg =  vipsimg.ThumbnailImage(99999, 400);
vipsimg.Jpegsave("out.jpg", 90);
vipsimg.Dispose();
sw.Stop();
```
I'm using Stopwatch to measure execution so it measures only resize operation not the whole exe start and end.

To measure vipsthumbnail.exe execution I use ptime.exe ([link](http://www.pc-tools.net/win32/ptime/)) that measures whole start and end of app and CLI still is better.

**Comment by jcupitt** [comment] 2020-05-03 11:11
One simple way to increase speed is to run several `vipsthumbnail` in parallel.

Most time is spent in libjpeg, which is single-threaded, so it's not possible to use all your cores. You'll find you can run quite a few thumbnail operations at once.

For example:

```
$ vipsheader ../nina.jpg 
../nina.jpg: 6048x4032 uchar, 3 bands, srgb, jpegload
$ for i in {1..1000}; do cp ../nina.jpg $i.jpg; done
$ time parallel vipsthumbnail -s 128 ::: *.jpg
real    0m11.940s
user    1m15.820s
sys 0m11.916s
```

That's thumbnailing 1,000 24mp JPEG images in 12s, so about 12ms per image.

**Comment by jcupitt** [comment] 2020-05-03 11:13
You're not using the fast path for thumbnailing. Try;

```C#
Stopwatch sw = new Stopwatch();
sw.Start();
NetVips.Image vipsimg = Image.Thumbnail(inputPath, 400);
vipsimg.Jpegsave("out.jpg", 90);
vipsimg.Dispose();
sw.Stop();
```

`ThumbnailImage` is very slow and only for images which you've loaded from some other source. Never use it if you can possibly avoid it.

**Comment by kleisauke** [comment] 2020-05-03 11:24
> I was not sure that it is using libjpeg-turbo because there is no such file `libjpeg-turbo.dll` in the file `vips-dev-w64-web-8.9.2.zip`

libjpeg-turbo uses the same library name (`libjpeg-62.dll`) as libjpeg  so it can be substituted at run time.

> `ThumbnailImage` is very slow and only for images which you've loaded from some other source. Never use it if you can possibly avoid it.

Perhaps we could give a warning [in the docs](https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-image) that this function should be avoided? I've seen this issue several times on the NetVips repository.

**Comment by flexphperia** [comment] 2020-05-03 11:25
@jcupitt 
Using your code (like below) it's still slower by 10ms than execution of `vipsthumbnail.exe` measured by ptime.exe :(
```
NetVips.Image vipsimg = Image.Thumbnail(inputPath, 400);
vipsimg.Jpegsave("out.jpg", 90);
```

**Comment by jcupitt** [comment] 2020-05-03 11:34
Good idea, I added a warning. Funny, I was sure there was a warning somewhere already, but obviously not.

@flexphperia I would look at thumbnailing several images in parallel.

240ms does seem slow -- I see:

```
$ time vipsthumbnail ../nina.jpg -s 400
real	0m0.121s
user	0m0.119s
sys	0m0.016s
```

ie. 120ms on this modest 2015 laptop. Perhaps your virus checker or file indexing system is adding overhead? Windows does also tend to be a little slower than linux.

**Comment by flexphperia** [comment] 2020-05-03 11:41
I have i7-8700 16GB Windows 10, AV disabled,  
`vipsthumbnail.exe 027.jpg --size "x400" -o out.jpg`
Time: **190ms**
So I won't get anything more out of it.

**Comment by jcupitt** [comment] 2020-05-03 11:52
I guess you're using the latest win32 build? There were some improvements last year.

Kleis, I think you were looking at a semi-static windows build at one point. Would that be any faster?

You could try adding `[strip]`. If there's a lot of metadata on your image, it might save a few ms.

```
vipsthumbnail something.jpg -s 400 -o x.jpg[strip]
```

Beyond that, run lots of vipsthumbnail in parallel, or perhaps try a linux host. I tried on an i7-6700 desktop running Ubuntu 19.10 and I see:

```
$ time vipsthumbnail nina.jpg -s 400
real	0m0.094s
user	0m0.088s
sys	0m0.016s
```

About 90ms for a 24mp image.

**Comment by flexphperia** [comment] 2020-05-03 11:59
@jcupitt 
Windows is a must in my app. `[strip]` gives me 1-3ms.
Unfortunately I can't use it in parallel. My application calls `vipsthumbnail.exe` about every 1 second to resize one image. 
What a shame Windows is almost twice as slow in this.
The performance of libvips is great compared to the ImageMagick I used before.

**Comment by kleisauke** [comment] 2020-05-03 14:01
@flexphperia Have you tried to disable the CPU frequency scaling while benchmarking this? On Windows this can be done like this:
![power_plan](https://user-images.githubusercontent.com/12746591/80915517-13127480-8d53-11ea-8035-e49af4653b82.png)

Which is effectively the same as doing this on Linux:
```bash
sudo cpupower frequency-set --governor performance
```

Alternatively, you can try to run your benchmark in BenchmarkDotNet which changes the power plan to `High-Performance` while running the benchmark, see: https://benchmarkdotnet.org/articles/configs/powerplans.html

> Kleis, I think you were looking at a semi-static windows build at one point. Would that be any faster?

Although it simplifies the packaging and  reduces the number of DLLs from 37 to 3, it didn't make the benchmark run faster. The last time I saw a nice speedup was when I ran the benchmark with #1492 included. The LLVM Windows builds (which is still WIP) could also speed this up a bit.

fwiw, sharp is also considering a semi-static Linux/Windows build, see: https://github.com/lovell/sharp-libvips/issues/39.

**Comment by flexphperia** [comment] 2020-05-03 14:35
@kleisauke tested as you told without power management. No changes to speed.
I'm using v.8.9.2 release.

**Comment by kleisauke** [comment] 2020-05-03 17:27
I tried a benchmark to see how much it differs between Linux and Windows.

**Test image**
https://en.wikipedia.org/wiki/File:Bao_Bao_Tree.jpg (24 megapixels)

**Benchmark**
```csharp
namespace NetVips.Benchmarks
{
    using BenchmarkDotNet.Attributes;

    [Config(typeof(Config))]
    public class Benchmark
    {
        [GlobalSetup]
        public void GlobalSetup()
        {
            // Disable libvips' operation cache
            NetVips.CacheSetMax(0);
        }

        [Benchmark(Description = "NetVips Thumbnail")]
        [Arguments("panda.jpg", "panda-thumb.jpg")]
        public void Thumbnail(string input, string output)
        {
            var im = Image.Thumbnail(input, width: 400);
            im.Jpegsave(output, q: 90);
        }
    }
}
```

Here are the results:
<details>
  <summary>Benchmark results</summary>
  
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.815 (1909/November2018Update/19H2)
Intel Core i5-8600K CPU 3.60GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.1.201
  [Host]            : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
  .Net Core 3.1 CLI : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT

Job=.Net Core 3.1 CLI  Toolchain=.NET Core 3.1  

```
|              Method |     input |          output |     Mean |   Error |  StdDev |
|-------------------- |---------- |---------------- |---------:|--------:|--------:|
| &#39;NetVips Thumbnail&#39; | panda.jpg | panda-thumb.jpg | 136.9 ms | 0.94 ms | 0.73 ms |

``` ini

BenchmarkDotNet=v0.12.1, OS=fedora 32
Intel Core i5-8600K CPU 3.60GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.1.103
  [Host]            : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT
  .Net Core 3.1 CLI : .NET Core 3.1.3 (CoreCLR 4.700.20.11803, CoreFX 4.700.20.12001), X64 RyuJIT

Job=.Net Core 3.1 CLI  Toolchain=.NET Core 3.1  

```
|              Method |     input |          output |     Mean |   Error |  StdDev |
|-------------------- |---------- |---------------- |---------:|--------:|--------:|
| &#39;NetVips Thumbnail&#39; | panda.jpg | panda-thumb.jpg | 128.0 ms | 0.40 ms | 0.37 ms |
</details>

So Linux beats Windows by 8.9 milliseconds (± 7% slowdown on Windows) which is reasonable. This was tested using the pre-built binaries from the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package.

@flexphperia Could you perhaps test the `vips-dev-w64-web-8.9.2-static.zip` binaries from the [build-win64-mxe repository](https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2)? You can also find these on NuGet within the `NetVips.Native.win-*` packages.

**Comment by flexphperia** [comment] 2020-05-03 17:58
@kleisauke 
My results of panda image.

NetVips (measured with stopwatch, net framework 4.7.2): **221ms**
```
Stopwatch sw = new Stopwatch();
sw.Start();
NetVips.Image vipsimg = Image.Thumbnail(sourceImgPath, 400);
vipsimg.Jpegsave(targetPath, 90);
vipsimg.Dispose();
sw.Stop();
```

CLI:
`vipsthumbnail.exe panda.jpg --size "400x" -o out.jpg`
MXE `vips-dev-w64-web-8.9.2-static.zip`: **213ms**
Default `vips-dev-w64-web-8.9.2.zip`: **172ms**

So I have faster CPU and im slower and also results from NetVips are slower than CLI.... weird.

**Comment by kleisauke** [comment] 2020-05-03 19:33
That's weird, are you sure it's picking the correct dependencies? For example, if there are multiple dependencies within the C# project that distribute `libjpeg-62.dll` it could choose the non-turbo version. 

You could try to use https://lucasg.github.io/Dependencies/ to check if all dependencies can be found and if they are picked up from the correct location.

I'll try to benchmark the `build-win64` version to see how much it differs compared to the `build-win64-mxe` version.

**Comment by flexphperia** [comment] 2020-05-04 07:21
@kleisauke 
The Dependencies application does not work in my case.
I use Visual Studio to create a project. 
When building, the DLL file does not copy to the right place so I need to copy three DLL files from the `NetVips.Native.win-x64.8.9.2` directory to the directory where my EXE file is located.
I have such NuGet packages installed:
![NuGet](https://i.ibb.co/WPffwN9/nuget.png)

I manage to improve my results when I do warmup iterations to pre-JIT.
```
//warmup JIT
NetVips.Image testImg1 = Image.Thumbnail(sourceImgPath, 600);
NetVips.Image testImg2 = Image.Thumbnail(sourceImgPath, 700);

//start measuring time
Stopwatch sw = new Stopwatch();
sw.Start();

NetVips.Image vipsimg = Image.Thumbnail(sourceImgPath, 400);
vipsimg.Jpegsave("out.jpg", 90);
vipsimg.Dispose();

sw.Stop();
Console.WriteLine("Time elapsed: ms" + sw.ElapsedMilliseconds);

```
Then I reach **150ms**, it's better than the previous result I wrote about but still comparing to your results relative to my stronger CPU is weak. I think I should reach about **100** - **110ms**. Then I would be pleased.

I can use ngen.exe (https://stackoverflow.com/a/20591941) to precompile the NET code but its use is quite difficult especially if you do not know the recipient machine which may have a higher version of the NET framework installed than I.

However, there is still a problem with a poor result.

Is there any other language binding for `libvips` that is easy to get a good result similar to native code and the learning curve is not staggering to write a simple application?

Here is the link to my package with the complete project from Visual Studio 2019 packed: [VS project](https://we.tl/t-qjnZiT4XxV)

**Comment by jcupitt** [comment] 2020-05-04 08:27
Could it be something simple like disc fragmentation?

If you've been developing an application which runs thumbnail once a second it could have become fragmented, and Windows is rather cautious about disc caching. You could try reading the file into memory, then timing `ThumbnailBuffer`.

Your warmup should include the `WriteToFile` or libvips won't actually process any pixels.

You could try the Python or Ruby bindings, but they won't beat the CLI for a simple thumbnailing task like this.

**Comment by flexphperia** [comment] 2020-05-04 09:24
I have already checked disk fragmentation. I also tested on HDD and SSD.
I think I can do nothing more, I stay with CLI. Thanks for your commitment and help and I hope this topic will be useful to someone in the future.

**Comment by kleisauke** [comment] 2020-05-13 19:48
I found a few problems within the MXE-based Windows builds that could affect performance (for e.g. libjpeg-turbo was built with YASM instead than NASM). Commit https://github.com/libvips/build-win64-mxe/commit/2228360255a191a40b18af0c2f7028ccb0ea1db1 (on the [`drop-vista-xp`](https://github.com/libvips/build-win64-mxe/tree/drop-vista-xp) branch) should resolve this.

The binaries can be found here: https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2-build2

I've re-tested the benchmark in https://github.com/libvips/libvips/issues/1637#issuecomment-623148515 and now I see:

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.836 (1909/November2018Update/19H2)
Intel Core i5-8600K CPU 3.60GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.1.202
  [Host]            : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
  .Net Core 3.1 CLI : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT

Job=.Net Core 3.1 CLI  Toolchain=.NET Core 3.1  

```
|              Method |     input |          output |     Mean |   Error |  StdDev |
|-------------------- |---------- |---------------- |---------:|--------:|--------:|
| &#39;NetVips Thumbnail&#39; | panda.jpg | panda-thumb.jpg | 128.3 ms | 1.07 ms | 0.83 ms |

So, on this benchmark, Linux and Windows runs at nearly the same speed. Let me know if this works for you.

**Comment by flexphperia** [comment] 2020-05-14 09:53
@kleisauke 
No changes, maybe 3-4ms better. 
Still default `vips-dev-w64-web-8.9.2.zip` is fastest.

MXE `vips-dev-w64-web-8.9.2-static.zip build2`: 203ms
Default `vips-dev-w64-web-8.9.2.zip`: 175ms

**Comment by kleisauke** [comment] 2020-05-14 10:55
It looks like you are measuring the CLI command including startup (`vips_init`) and shutdown (`vips_shutdown`) overhead. Could you try this instead?

```bash
vipsthumbnail.exe panda.jpg --size "400x" -o out.jpg --vips-progress
```

For example, I see this in both MXE and non-MXE builds:
```
vipsthumbnail.exe temp-18: 400 x 267 pixels, 6 threads, 400 x 16 tiles, 128 lines in buffer
vipsthumbnail.exe temp-18: done in 0,133s
```

There is indeed a difference (± 30 milliseconds) when measuring the entire execution time (i.e. including startup and shutdown overhead) between the MXE and non-MXE build, I see this at the moment:
<details>
  <summary>Details</summary>
  
MXE:
```powershell
$ Measure-Command { .\vipsthumbnail.exe panda.jpg --size "400x" -o out.jpg }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 184
Ticks             : 1841166
TotalDays         : 2,13097916666667E-06
TotalHours        : 5,11435E-05
TotalMinutes      : 0,00306861
TotalSeconds      : 0,1841166
TotalMilliseconds : 184,1166
```

Non-MXE:
```powershell
$ Measure-Command { .\vipsthumbnail.exe panda.jpg --size "400x" -o out.jpg }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 152
Ticks             : 1525742
TotalDays         : 1,76590509259259E-06
TotalHours        : 4,23817222222222E-05
TotalMinutes      : 0,00254290333333333
TotalSeconds      : 0,1525742
TotalMilliseconds : 152,5742
```
</details>

I'll look into this further. Thanks for noticing!

**Comment by flexphperia** [comment] 2020-05-16 07:29
Ok, my new tests here:

Default `vips-dev-w64-web-8.9.2.zip`: 
`--vips-progress`: **133ms**
`ptime.exe`: **174ms**

MXE `vips-dev-w64-web-8.9.2-static.zip build2`:
`--vips-progress`: 135ms
`ptime.exe`: 206ms

MXE `vips-dev-w64-web-8.9.2.zip build2`:
`--vips-progress`: 155ms
`ptime.exe`: 236ms

The standard version still wins for me.

@jcupitt  @kleisauke 
I have an idea how to speed up Windows CLI when image processing is needed at irregular intervals.
It would be nice if `vipsthumbnail.exe` and `vips.exe` had "stay_open" mode.
ExifTool by Phil Harvey (https://exiftool.org/) has this mode. This greatly improved the performance in my tests, as well as here you could get the operation time reduced by startup and shutdown overhead.

In short from ExifTool docs:

> -stay_open FLAG

> If FLAG is 1 or True, causes exiftool keep reading from the -@ ARGFILE even after reaching the end of file. This feature allows calling applications to pre-load exiftool, thus avoiding the overhead of loading exiftool for each command. The procedure is as follows:
> 
> 1) Execute exiftool -stay_open True -@ ARGFILE, where ARGFILE is the name of an existing (possibly empty) argument file or - to pipe arguments from the standard input.
> 
> 2) Write exiftool command-line arguments to ARGFILE, one argument per line (see the -@ option for details).
> 
> 3) Write -execute\n to ARGFILE, where \n represents a newline sequence. (Note: You may need to flush your write buffers here if using buffered output.) Exiftool will then execute the command with the arguments received up to this point, send a "{ready}" message to stdout when done (unless the -q or -T option is used), and continue trying to read arguments for the next command from ARGFILE. To aid in command/response synchronization, any number appended to the -execute option is echoed in the "{ready}" message. For example, -execute613 results in "{ready613}".
> 
> 4) Repeat steps 2 and 3 for each command.
> 
> 5) Write -stay_open\nFalse\n to ARGFILE when done. This will cause exiftool to process any remaining command-line arguments then exit normally.

**Comment by kleisauke** [comment] 2020-05-16 16:37
It appears that the speed improvement you noticed is due to GLib using a statically built dummy implementation of libintl/gettext that disables all i18n features.
https://gitlab.gnome.org/GNOME/glib/-/blob/20fb5bf868added5aec53c013ae85ec78ba2eedc/meson.build#L1946-1948
https://github.com/frida/proxy-libintl

Somehow I couldn't reproduce this when building the [build-win64 repository](https://github.com/libvips/build-win64) in a Docker container, although the released binaries were built with this implementation:
```bash
$ curl -LO https://github.com/libvips/libvips/releases/download/v8.9.2/vips-dev-w64-web-8.9.2.zip
$ unzip vips-dev-w64-web-8.9.2.zip
$ cat vips-dev-8.9/include/libintl.h | grep PROXY_LIBINTL
# define PROXY_LIBINTL_GNUC_FORMAT(arg_idx) __attribute__((__format_arg__(arg_idx)))
# define PROXY_LIBINTL_GNUC_FORMAT(arg_idx)
```
I had an attempt to switch the MXE build to this dummy implementation of libintl as well. See commit: https://github.com/libvips/build-win64-mxe/commit/1a39f92fdf239702da7b38e765336d20303399a0

The binaries, which are suffixed with `-build3`, can be found here:
https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2-build3

I now see:
```powershell
$ Measure-Command { .\vipsthumbnail.exe panda.jpg --size "400x" -o out.jpg }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 150
Ticks             : 1509389
TotalDays         : 1,74697800925926E-06
TotalHours        : 4,19274722222222E-05
TotalMinutes      : 0,00251564833333333
TotalSeconds      : 0,1509389
TotalMilliseconds : 150,9389
```

So, this operation, runs at the same speed as the non-MXE builds.

@jcupitt Do you think this could cause side effects? This effectively deprecate all i18n features, so everything is English (en_GB), for e.g. [this comment](https://github.com/libvips/build-win64/blob/aade6cbd1c3292395f36cfbc7721971759c01c78/8.9/package-vipsdev.sh#L61-L62) is therefore no longer valid.

**Comment by jcupitt** [comment] 2020-05-16 17:08
I think I remember turning off i18n for win32 libvips, but not all the details.

You need to ship the `.po` files and you probably need something to help gettext find them all relative to the `bin` directory. The annoyance and cost didn't seem worthwhile since we don't really have much in the way of useful i18n at the moment.

The nip2 win binary does support i18n since it needs a lot of extra files anyway. Perhaps that comment is left over from that build.

**Comment by flexphperia** [comment] 2020-05-16 18:52
Now is better, it gives the same results as default build.

MXE `vips-dev-w64-web-8.9.2-build3-static.zip`:
`--vips-progress`: 134ms
`ptime.exe`: 172ms

MXE `vips-dev-w64-web-8.9.2-build3.zip`:
`--vips-progress`: 134ms
`ptime.exe`: 174ms

**Comment by kleisauke** [comment] 2020-05-20 14:20
Thanks for testing! I'm glad the numbers are the same now.

I've merged this enhancement to master with commit https://github.com/libvips/build-win64-mxe/commit/1964b876290d151c124abd80902a7b12fe464184. This update will be included in the forthcoming NetVips.Native release.

I'll check if Linux builds can benefit from this as well. I also plan to do a PR for the standard builds since it still ships with `libintl.dll` (and `libiconv-2.dll`).

@jcupitt Ah, that makes sense. If you want, I can have a look at the nip2 win build. I occasionally use `nip2-8.7.0-setup.zip` on Windows, so it would be nice if this is updated to the latest libvips versions (perhaps it's possible to swap the binaries in the installed directory as well, but I haven't tried that yet).

**Comment by jcupitt** [comment] 2020-05-20 14:38
Sure, please attack the nip2 build if you need something to do.

I've been trying to update it to 64 bits and to use the same vips.modules as libvips (to save a lot of annoying duplication). There's a `add-nip2-again` branch on `build-win64` with the work I did.

It's been a while since I last looked, but my memory is that it mostly works, except for text rendering with `vips_text()` and perhaps goffice (used for drawing graphs). I made a few other improvements to the build system as well, to make supporting multiple targets easier.

It also uses that terrible nullsoft installer, of course, but I've not tried to fix that.

**Comment by jcupitt** [comment] 2020-06-14 18:28
I think this is done, I'll close.

**Closed by jcupitt** 2020-06-14 18:28 UTC
Labels: question

**Comment by sergeevabc** [comment] 2021-06-09 08:37
Sorry for digging up this old thread, but I see it is related to even older thing I am looking for, which is XP-supported binary of Vips. According to your posts, my best best is [vips-dev-w32-all-8.9.2.zip][1]. Thanks God, it is still available for download. I wonder if it is the latest version? I see there are some [drop-xp][2] branch and [build-2][3] without binaries.

[1]: https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2 
[2]: https://github.com/libvips/build-win64-mxe/tree/drop-vista-xp
[3]: https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.2-build2

**Comment by jcupitt** [comment] 2021-06-09 08:42
Hi again, could you open new issues / discussions rather than posting on old ones? It's best if each issue is just about one topic.

Re. win xp, sorry, we probably don't support that any more. You can always build it yourself, of course.
