### ISSUE TITLE
dzsave not consistent with aperio

### ISSUE THREAD

**Issue by Mamikon95** [libvips/libvips#1532] opened 2020-01-21 09:19 UTC
Hi! I save the tiff file via dzsave, it looks like this in openseadragon ...
I open in ImageScope Aperio is as follows ...
In addition, when scaling in openseadragon, the scale is not so large, a maximum of 13 levels. But in aperio, scaling is better.
Questions:
1. How to make dzsave the same as in aperio?
2. How to make dzsave create more levels and zoom?

**Comment by jcupitt** [comment] 2020-01-21 10:15
Hello @Mamikon95,

I'm not sure I understand. Do you want dzsave to make pyramids that work with the Aperio viewer? Or do you want dzsave + openseadragon to look more like the Aperio viewer? I don't know anything about the Aperio viewer, can it even display deepzoom pyramids?

What do you mean when you say you want more zoom levels? What kind of zooming is not working? Do you want smoother zooming? Do you want the ability to zoom out further? Or maybe in further?

**Comment by Mamikon95** [comment] 2020-01-21 11:15
> Hello @Mamikon95,
> 
> I'm not sure I understand. Do you want dzsave to make pyramids that work with the Aperio viewer? Or do you want dzsave + openseadragon to look more like the Aperio viewer? I don't know anything about the Aperio viewer, can it even display deepzoom pyramids?
> 
> What do you mean when you say you want more zoom levels? What kind of zooming is not working? Do you want smoother zooming? Do you want the ability to zoom out further? Or maybe in further?

I will slightly change my question))

http://prntscr.com/qqpcot

I have a .scn file. It has a label image and basic content.
vips dzsave x.scn test / --vips-progress
This command makes the label image pyramidal. I want to pyramid the main content. How can this be done?

**Comment by jcupitt** [comment] 2020-01-21 11:31
Huh that's odd, I wonder how the main image and the additional images became swapped?

You can view the whole header with:

```
$ vipsheader -a Leica-1.scn 
Leica-1.scn: 53130x153470 uchar, 4 bands, srgb, openslideload
width: 53130
height: 153470
bands: 4
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: Leica-1.scn
vips-loader: openslideload
slide-level: 0
leica.aperture: 0.4
leica.barcode: 04050629C
leica.creation-date: 2011-05-31T09:43:06.873Z
leica.device-model: Leica SCN400;Leica SCN
leica.device-version: 1.4.0.9691 2011/03/30 10:30:59;1.4.0.9708
leica.illumination-source: brightfield
leica.objective: 20
openslide.bounds-height: 38432
openslide.bounds-width: 36832
openslide.bounds-x: 10778
openslide.bounds-y: 35096
openslide.level-count: 5
openslide.level[0].downsample: 1
openslide.level[0].height: 153470
openslide.level[0].width: 53130
openslide.level[1].downsample: 3.9998986524159981
openslide.level[1].height: 38368
openslide.level[1].width: 13283
openslide.level[2].downsample: 15.998992404088622
openslide.level[2].height: 9592
openslide.level[2].width: 3321
openslide.level[3].downsample: 63.927109191868013
openslide.level[3].height: 2401
openslide.level[3].width: 831
openslide.level[4].downsample: 255.3952147062588
openslide.level[4].height: 601
openslide.level[4].width: 208
openslide.mpp-x: 0.5
openslide.mpp-y: 0.5
openslide.objective-power: 20
openslide.quickhash-1: f600ae1d83abaa21b6fda9284ff35a51d7031f60854b5674fac88c8ac6d66298
openslide.region[0].height: 38432
openslide.region[0].width: 36832
openslide.region[0].x: 10778
openslide.region[0].y: 35096
openslide.vendor: leica
tiff.ResolutionUnit: centimeter
tiff.XResolution: 20000
tiff.YResolution: 20000
slide-associated-images: macro
```

You can see all the levels, plus the set of additional images (just a macro shot in this case).

What do you get for your `scn`?

**Comment by jcupitt** [comment] 2020-01-21 11:31
That's this test image: http://openslide.cs.cmu.edu/download/openslide-testdata/Leica/

**Comment by Mamikon95** [comment] 2020-01-21 11:35
> Huh that's odd, I wonder how the main image and the additional images became swapped?
> 
> You can view the whole header with:
> 
> ```
> $ vipsheader -a Leica-1.scn 
> Leica-1.scn: 53130x153470 uchar, 4 bands, srgb, openslideload
> width: 53130
> height: 153470
> bands: 4
> format: uchar
> coding: none
> interpretation: srgb
> xoffset: 0
> yoffset: 0
> xres: 1
> yres: 1
> filename: Leica-1.scn
> vips-loader: openslideload
> slide-level: 0
> leica.aperture: 0.4
> leica.barcode: 04050629C
> leica.creation-date: 2011-05-31T09:43:06.873Z
> leica.device-model: Leica SCN400;Leica SCN
> leica.device-version: 1.4.0.9691 2011/03/30 10:30:59;1.4.0.9708
> leica.illumination-source: brightfield
> leica.objective: 20
> openslide.bounds-height: 38432
> openslide.bounds-width: 36832
> openslide.bounds-x: 10778
> openslide.bounds-y: 35096
> openslide.level-count: 5
> openslide.level[0].downsample: 1
> openslide.level[0].height: 153470
> openslide.level[0].width: 53130
> openslide.level[1].downsample: 3.9998986524159981
> openslide.level[1].height: 38368
> openslide.level[1].width: 13283
> openslide.level[2].downsample: 15.998992404088622
> openslide.level[2].height: 9592
> openslide.level[2].width: 3321
> openslide.level[3].downsample: 63.927109191868013
> openslide.level[3].height: 2401
> openslide.level[3].width: 831
> openslide.level[4].downsample: 255.3952147062588
> openslide.level[4].height: 601
> openslide.level[4].width: 208
> openslide.mpp-x: 0.5
> openslide.mpp-y: 0.5
> openslide.objective-power: 20
> openslide.quickhash-1: f600ae1d83abaa21b6fda9284ff35a51d7031f60854b5674fac88c8ac6d66298
> openslide.region[0].height: 38432
> openslide.region[0].width: 36832
> openslide.region[0].x: 10778
> openslide.region[0].y: 35096
> openslide.vendor: leica
> tiff.ResolutionUnit: centimeter
> tiff.XResolution: 20000
> tiff.YResolution: 20000
> slide-associated-images: macro
> ```
> 
> You can see all the levels, plus the set of additional images (just a macro shot in this case).
> 
> What do you get for your `scn`?

test/x.scn: 1616x4668 uchar, 3 bands, srgb, tiffload
width: 1616
height: 4668
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 60.833
yres: 60.833
filename: test/x.scn
vips-loader: tiffload
n-pages: 9
resolution-unit: cm
orientation: 1

**Comment by jcupitt** [comment] 2020-01-21 11:42
Ah OK, your libvips does not have openslide support. You need to enable openslide before you can process slide images.

**Comment by Mamikon95** [comment] 2020-01-21 11:44
> Ah OK, your libvips does not have openslide support. You need to enable openslide before you can process slide images.

how can i enable openslide?

**Comment by jcupitt** [comment] 2020-01-21 11:48
It depends. Did you build libvips yourself, or is it from some repository? What platform are you using?

**Comment by Mamikon95** [comment] 2020-01-21 11:51
> It depends. Did you build libvips yourself, or is it from some repository? What platform are you using?

Operating System: CentOS Linux 7 (Core) Kernel: Linux 2.6.32-042stab141.3 Architecture: x86-64

I collected it myself, according to this instruction http://prntscr.com/qqq0i8

**Comment by jcupitt** [comment] 2020-01-21 11:52
I would check the output of configure carefully and make sure you have "yes" next to openslide.

If you don't, you need the openslide-devel package, or you need to build openslide yourself from source.

**Comment by Mamikon95** [comment] 2020-01-21 12:02
*I would check the output of configure carefully and make sure you have "yes" next to openslide.*


which command can watch it?

**Comment by Mamikon95** [comment] 2020-01-21 12:33
> If you don't, you need the openslide-devel package, or you need to build openslide yourself from source.

I downloaded the package installed
https://centos.pkgs.org/7/epel-x86_64/openslide-devel-3.4.1-1.el7.x86_64.rpm.html

right now shows that openslide is enabled
http://prntscr.com/qqqpa8

But still the label image is pyramidizing

**Comment by Mamikon95** [comment] 2020-01-21 12:47
http://prntscr.com/qqqz5h

**Comment by jcupitt** [comment] 2020-01-21 12:51
Did you `make` and `make install` as well?

**Comment by Mamikon95** [comment] 2020-01-21 12:56
> Did you `make` and `make install` as well?

yes but nothing has changed

**Comment by Mamikon95** [comment] 2020-01-21 13:25
http://prntscr.com/qqrnxa

**Comment by jcupitt** [comment] 2020-01-21 13:54
I guess you probably have two vips installed now. 

Are you installing to `/usr/local`? I would remove that version and verify that you have no vips anywhere, then reinstall. 

Check that you are running the correct vips:

```
$ which vips
```

Check that it is using the correct shared library:

```
$ ldd $(which vips) | grep vips
```

**Comment by Mamikon95** [comment] 2020-01-21 14:32
> ldd $(which vips) | grep vips

I removed the VIPs, installed version 8.9
but nothing has changed :(

**Comment by Mamikon95** [comment] 2020-01-21 14:33
> ldd $(which vips) | grep vips

http://prntscr.com/qqsx9k

**Comment by jcupitt** [comment] 2020-01-21 14:34
Try this:

```
vips openslideload
```

I think you say you see an error, is that right? If so, you must be executing an old version of `vips`. Try:

```
which vips
```

What do you see? That should be the path to the old version you are running by mistake. Remove that version and try again.

**Comment by Mamikon95** [comment] 2020-01-21 14:36
> What do you see? That should be the path to the old version you are running by mistake. Remove that version and try again.

vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   attach-associated - Attach all asssociated images, input gboolean
                        default: false
   level        - Load this level from the file, input gint
                        default: 0
                        min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
                        default: false
   associated   - Load this associated image, input gchararray
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
                        default: false
   access       - Required access pattern for this file, input VipsAccess
                        default: random
                        allowed: random, sequential, sequential-unbuffered
   fail         - Fail on first error, input gboolean
                        default: false

**Comment by jcupitt** [comment] 2020-01-21 14:37
Oh, OK, so it's working! 

Now try `vipsheader -a something.scn` and verify that you see all the correct metadata.

Then try running `dzsave` again.

**Comment by Mamikon95** [comment] 2020-01-21 14:39
> Oh, OK, so it's working!
> 
> Now try `vipsheader -a something.scn` and verify that you see all the correct metadata.
> 
> Then try running `dzsave` again.

x.scn: 1616x4668 uchar, 3 bands, srgb, tiffload_source
width: 1616
height: 4668
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 60.833
yres: 60.833
filename: x.scn
vips-loader: tiffload_source

**Comment by Mamikon95** [comment] 2020-01-21 14:39
openslide works, but dzsave still processes the image label.

**Comment by jcupitt** [comment] 2020-01-21 14:45
Ah, is this 8.9.0? There is a bug in the CLI where it fails to select openslide correctly.

Try:

```
vips openslideload x.scn x.dz
```

And it should write `x_files` and `x.dzi`.

**Comment by Mamikon95** [comment] 2020-01-21 14:54
> And it should write `x_files` and `x.dzi`

Thank you, it seems to work)) if I switch to version 8.8 you don’t have to openlide to write in the command anymore?

**Comment by jcupitt** [comment] 2020-01-21 14:55
\o/ woo!

8.9.1 has a fix for this, but it's not quite done yet. Another few days.

**Comment by Mamikon95** [comment] 2020-01-23 08:19
> 8.9.1 has a fix for this, but it's not quite done yet. Another few days.

Please tell me, is there a problem in previous versions?

**Comment by jcupitt** [comment] 2020-01-23 08:41
It's just a bug in 8.9.0 caused by the new loader system.

**Comment by Mamikon95** [comment] 2020-01-23 08:42
> It's just a bug in 8.9.0 caused by the new loader system.

Ok, thanks))

**Closed** 2020-03-10 16:00 UTC
Labels: question
