### ISSUE TITLE
heif load error

### ISSUE THREAD

**Issue by yanxianrui** [libvips/libvips#1888] opened 2020-11-18 15:25 UTC
some pictures saved by vips_heifsave_buffer can not be loaded by vips_heifload_buffer
error occurs when i use vips copy to transfrom this picture to heif and thumbnail it.

my test file:
[1.zip](https://github.com/libvips/libvips/files/5561106/1.zip)

errors:
xxx$ vips copy 1.jpg 1-80.heif[strip,Q=80]
xxx$ vipsthumbnail 1-80.heif 
(vipsthumbnail:26915): VIPS-WARNING **: heifload: ignoring nclx profile
(vipsthumbnail:26915): VIPS-WARNING **: heifload: ignoring nclx profile
(vipsthumbnail:26915): VIPS-WARNING **: heifload: ignoring nclx profile
(vipsthumbnail:26915): VIPS-WARNING **: heifload: ignoring nclx profile
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 0
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 0
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 0
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 10
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 20
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 30
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 40
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 50
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 60
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 70
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 80
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 90
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 100
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 110
(vipsthumbnail:26915): VIPS-WARNING **: error in tile 0 x 120
vipsthumbnail: unable to thumbnail 1-80.heif
1-80.heif: bad seek to 93963
1-80.heif: bad seek to 93963
1-80.heif: bad seek to 93963
heifload: bad image dimensions on decode

vips version:  8.12
libheif:  1.9.1
x265: 1.9
libde265:  1.0.2
os: ubuntu 12.04

I'm new to libvips.   thanks a lot for any reply.

**Comment by jcupitt** [comment] 2020-11-18 16:10
Hello @yanxianrui,

It's working for me:

```
john@yingna ~/pics $ vips copy 1.jpg 1-80.heif[strip,Q=80]
john@yingna ~/pics $ vipsthumbnail 1-80.heif
john@yingna ~/pics $ 
```

libheif 1.6.1
libvips 8.11
x265 3.2.1
libde265 1.0.4
ubuntu 20.04

I'm not sure which of your packages you need to update though. Did you mean libvips 8.11? Your ubuntu sounds too old as well. Your x265 seems very old too.

Here's the `1-80.heif` that I made:

[1-80.heif.zip](https://github.com/libvips/libvips/files/5561254/1-80.heif.zip)

If you can vipsthumbnail that I guess the problem must be in your x265.

**Comment by yanxianrui** [comment] 2020-11-18 16:48
sorry it's vips  8.10.2 and  thank you for your prompt reply. 
I've tried x265 3.3 before but it doesn't work.  
I‘II update all my packages to your version to try except my old ubuntu. :sob: I must use it.

**Comment by kleisauke** [comment] 2020-11-19 12:50
I think this is a duplicate of https://github.com/libvips/libvips/issues/1808. Since commit https://github.com/strukturag/libheif/commit/c6f794513595a5f6d9996137985e5bdf616f5c2c (i.e. libheif >= v1.8.0) an odd-sized HEIF file is written with a `clap` box to crop away the padding border. However, this causes problems when libvips tries to load such images, as it requires that the frame size corresponds with the size specified in the container.

A similar issue can be observed with Google Chrome and libheif-encoded AVIF images smaller than 16×16 pixels (only when libheif is built with aom).

**Comment by jcupitt** [comment] 2020-11-19 13:48
Ah, I understand! Sorry Kleis, I've not been following that issue.

I suppose libvips needs a patch for this change?

**Comment by kleisauke** [comment] 2020-11-19 16:04
Probably some additional clipping code needs to be added.

**Comment by yanxianrui** [comment] 2020-11-20 09:43
Hello  @jcupitt 
I can vipsthumbnail the heif file you made.  And no error occurs when I  try to use libheif 1.6.1.  
thanks a lot for your reply and info. 
should I close this question or wait for a patch ?

**Comment by yanxianrui** [comment] 2020-11-20 09:59
> I think this is a duplicate of #1808. Since commit [strukturag/libheif@c6f7945](https://github.com/strukturag/libheif/commit/c6f794513595a5f6d9996137985e5bdf616f5c2c) (i.e. libheif >= v1.8.0) an odd-sized HEIF file is written with a `clap` box to crop away the padding border. However, this causes problems when libvips tries to load such images, as it requires that the frame size corresponds with the size specified in the container.
> 
> A similar issue can be observed with Google Chrome and libheif-encoded AVIF images smaller than 16×16 pixels (only when libheif is built with aom).

thand you for your info. I change libheif to 1.6.1 and it works.

**Comment by jaubourg** [comment] 2020-11-24 17:55
@jcupitt dunno if it's related but I'm getting a: `source: bad seek to 1272289` when loading the following heic file: [IMG_2631.HEIC](https://s3.eu-west-3.amazonaws.com/assets.twicpics.com/tests/IMG_2631.HEIC).

It's from "the wild" so I have no clue how it was created/saved.

I'm using a custom build with:
- libde265 1.0.8
- libheif 1.9.1
- libvips 8.10.2
- x265 3.4

I cannot seem to find libvips 8.11 and I'm unable to test with it, was it released some place else than github?

**Comment by jcupitt** [comment] 2020-11-24 22:15
Hi @jaubourg, that looks like a different issue. I tried with git master libheif and their `heif-convert` example reads your file correctly, but libvips fails. 

Could you open a new issue please?

**Comment by jaubourg** [comment] 2020-11-24 23:03
@jcupitt done! ;)

**Closed** 2020-11-29 05:18 UTC
Labels: question
