### ISSUE TITLE
8.15.0: ARW images throw `Input file has corrupt header`

### ISSUE THREAD

**Issue by mertalev** [libvips/libvips#3777] opened 2023-12-12 03:57 UTC
## Bug report

As of 8.15.0 (specifically when built with [this](https://github.com/libvips/libvips/commit/001a22b1895b252ce16a5f893231f9d1ccfa0736) commit or later, including main), attempting to process ARW images with sharp throws an error. 

**To Reproduce**
1. With the sample image provided [here](https://github.com/immich-app/immich/issues/5625), run the following MCVE:

```
const sharp = require('sharp');
sharp('DSC04964.ARW').toFile('test_arw.jpg');
```

**Expected behavior**
It should create the output image without error.

**Actual behavior**
It throws the following error:

```
Error: Input file has corrupt header: magickload: Magick: TIFF directory is missing required "ImageLength" field. MissingRequired' @ error/tiff.c/TIFFErrors/599 (null)
magickload: Magick: unable to read image data `DSC04964.ARW' @ error/tiff.c/ReadTIFFImage/1299 (null)
```

**Environment**
 - libvips: 8.15.0 (built with `meson setup build --buildtype=release --libdir=lib -Dintrospection=disabled -Dtiff=disabled`)
 - ImageMagick: 7.1.1-13
 - sharp: 0.33.0
 - libraw: 0.21.1
 - OS: Debian Bookworm
 
For a full reproduction of the environment, you can use this Docker image: 

`ghcr.io/immich-app/immich-server:main@sha256:4cee4328560af82fa519c1084b0d35fc7bf74f2e68f38a7aca68e4c254e59662`

**Additional context**

Building without the `-Dtiff=disabled` flag seems to produce the same result in this case.

Additionally, running ImageMagick directly with `convert DSC04964.ARW test_arw.jpg` successfully produces the output file.

I also tested a NEF image ([here](https://raw.pixls.us/getfile.php/5208/nice/Nikon%20-%20D3S%20-%2012bit%20uncompressed%20(3:2).NEF)) that produces the same issue described in #3380 when building with this commit or later, which I think suggests a common root cause.

**Comment by kleisauke** [comment] 2023-12-12 09:35
This issue is similar to #3380. The problem is that ImageMagick doesn't have any buffer recognizers for these image formats and only relies on the file extension as a hint. You can reproduce this on CLI with:
```console
$ cp DSC04964.ARW x
$ convert x x.jpg
convert: Unknown field with tag 50341 (0xc4a5) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
convert: TIFF directory is missing required "ImageLength" field. `MissingRequired' @ error/tiff.c/TIFFErrors/599.
convert: no images defined `x.jpg' @ error/convert.c/ConvertImageCommand/3362.
```

Here's a candidate patch for libvips that should fix this:
<details>
  <summary>Details</summary>

```diff
--- a/libvips/foreign/magick.c
+++ b/libvips/foreign/magick.c
@@ -115,8 +115,17 @@ magick_sniff(const unsigned char *bytes, size_t length)
 	const MagicInfo *magic_info = GetMagicInfo(bytes, length, exception);
 	magick_destroy_exception(exception);
 
-	if (magic_info)
-		return GetMagicName(magic_info);
+	if (magic_info) {
+		const char *magic_name = GetMagicName(magic_info);
+
+		/* Avoid using TIFF as a format hint since RAW/DNG images often
+		 * share the same magic signature as TIFF.
+		 */
+		if (magic_name &&
+			g_ascii_strcasecmp(magic_name, "TIFF") != 0) {
+			return magic_name;
+		}
+	}
 #endif
 
 	return NULL;
```
</details>

**Comment by jcupitt** [comment] 2023-12-12 12:05
That's a good idea @kleisauke, I added this to 8.15 and master.

The magick6 that comes with ubuntu 23.10 doesn't support RAW images (due to `ufraw-batch` going away), but with this patch it works with magic7 main (they've switched to `dcraw` I think):

```
$ vips copy DSC04964.ARW x.jpg 

(vips:1297337): VIPS-WARNING **: 12:02:49.498: Unknown field with tag 50341 (0xc4a5) encountered
```

**Comment by jcupitt** [comment] 2023-12-12 12:07
This will be in 8.15.1, thanks for the report @mertalev

**Closed by jcupitt** 2023-12-12 12:07 UTC
Labels: bug
