### ISSUE TITLE
heifsave_buffer does not seem to take quality into account when using VIPS_FOREIGN_HEIF_COMPRESSION_AV1

### ISSUE THREAD

**Issue by jaubourg** [libvips/libvips#1757] opened 2020-08-01 22:21 UTC
**Describe the bug**
When changing quality (`Q`) when calling `heifsave_buffer` with `compression` set to `VIPS_FOREIGN_HEIF_COMPRESSION_AV1`, the resulting buffer/file size is always the same.

**To Reproduce**
1. Compile libvips with libheif support (the latter having been compiled with libaom support)
2. Try the following code:
    ```C++
    image.heifsave_buffer(
        VImage::option()
            ->set( "Q", quality )
    );
    ```
    File size will changes as `quality` changes.
3. Try this variation:
    ```C++
    image.heifsave_buffer(
        VImage::option()
            ->set( "compression", VIPS_FOREIGN_HEIF_COMPRESSION_AV1 )
            ->set( "Q", quality )
    );
    ```
    File size is always the same no matter the value quality is set to.

**Expected behavior**
I expect the file size to change when quality changes.

**Actual behavior**
The file size does not change.

**Environment**
Linux x86-64 docker
libvips 8.9.2

**Additional context**
Trying to support AVIF in my service. I tried sharp and it seems to exhibit the exact same behaviour.
It may be an issue up the food chain with libheif but I'd like to make sure it's not something that needs fixing in libvips.

**Comment by lovell** [comment] 2020-08-02 15:05
This looks like a libheif bug.

```sh
$ heif-enc --avif -q 25 -o out-25.avif input.jpg
$ heif-enc --avif -q 75 -o out-75.avif input.jpg
$ ls *.avif
123239 out-25.avif
123239 out-75.avif
```
My best guess is that `aom_set_default_parameters` is being called too late and overriding user-supplied values, so the "quality" will always be the default value of 50.

https://github.com/strukturag/libheif/blob/436d1c4078d27a5ff3b31e98a378b328894c1efb/libheif/heif_encoder_aom.cc#L590 

Please can you report this upstream with relevant version numbers etc.

**Comment by lovell** [comment] 2020-08-04 08:32
Confirmed as upstream bug so closing this issue, thanks for reporting.

**Closed by lovell** 2020-08-04 08:32 UTC
Labels: bug
