### ISSUE TITLE
vips 8.15.2 failed to build with latest xcode

### ISSUE THREAD

**Issue by chenrui333** [libvips/libvips#3901] opened 2024-03-16 23:26 UTC
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
clang -Ilibvips/vips-heif.dylib.p -Ilibvips -I../libvips -I. -I.. -Ilibvips/include -I../libvips/include -Ilibvips/include/vips -I/opt/homebrew/Cellar/pcre2/10.43/include -I/opt/homebrew/Cellar/glib/2.80.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.80.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/glib/2.80.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/ffi -I/opt/homebrew/Cellar/libarchive/3.7.2/include -I/opt/homebrew/Cellar/fftw/3.3.10_1/include -I/opt/homebrew/Cellar/cfitsio/4.4.0/include -I/opt/homebrew/Cellar/libimagequant/4.3.0/include -I/opt/homebrew/Cellar/cgif/0.3.2/include -I/opt/homebrew/Cellar/libexif/0.6.24/include -I/opt/homebrew/Cellar/mozjpeg/4.1.5/include -I/opt/homebrew/Cellar/libspng/0.7.4/include -I/opt/homebrew/Cellar/webp/1.3.2/include -I/opt/homebrew/Cellar/webp/1.3.2/include/webp -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.15.0/include -I/opt/homebrew/Cellar/libxau/1.0.11/include -I/opt/homebrew/Cellar/libxdmcp/1.1.5/include -I/opt/homebrew/Cellar/libxcb/1.16.1/include -I/opt/homebrew/Cellar/libx11/1.8.7/include -I/opt/homebrew/Cellar/libxext/1.3.6/include -I/opt/homebrew/Cellar/libxrender/0.9.11/include -I/opt/homebrew/Cellar/pixman/0.42.2/include/pixman-1 -I/opt/homebrew/Cellar/cairo/1.18.0/include/cairo -I/opt/homebrew/Cellar/fribidi/1.0.13/include/fribidi -I/opt/homebrew/Cellar/graphite2/1.3.14/include -I/opt/homebrew/Cellar/harfbuzz/8.3.0_1/include/harfbuzz -I/opt/homebrew/Cellar/pango/1.52.1/include/pango-1.0 -I/opt/homebrew/Cellar/xorgproto/2023.2/include -I/opt/homebrew/Cellar/xz/5.6.1/include -I/opt/homebrew/Cellar/zstd/1.5.5/include -I/opt/homebrew/Cellar/libtiff/4.6.0/include -I/opt/homebrew/Cellar/gdk-pixbuf/2.42.10_1/include/gdk-pixbuf-2.0 -I/opt/homebrew/Cellar/librsvg/2.57.2/include/librsvg-2.0 -I/opt/homebrew/Cellar/libmatio/1.5.26/include -I/opt/homebrew/opt/hdf5/include -I/opt/homebrew/Cellar/little-cms2/2.16/include -I/opt/homebrew/Cellar/imath/3.1.11/include -I/opt/homebrew/Cellar/imath/3.1.11/include/Imath -I/opt/homebrew/Cellar/openexr/3.2.3/include -I/opt/homebrew/Cellar/openexr/3.2.3/include/OpenEXR -I/opt/homebrew/Cellar/openjpeg/2.5.2/include/openjpeg-2.5 -I/opt/homebrew/Cellar/highway/1.1.0/include -I/opt/homebrew/Cellar/libvmaf/3.0.0/include -I/opt/homebrew/Cellar/libvmaf/3.0.0/include/libvmaf -I/opt/homebrew/Cellar/aom/3.8.2/include -I/opt/homebrew/Cellar/libde265/1.0.15/include -I/opt/homebrew/Cellar/x265/3.5/include -I/opt/homebrew/Cellar/libheif/1.17.6/include -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=gnu99 -O3 -DG_DISABLE_CAST_CHECKS -DG_DISABLE_CHECKS -DG_DISABLE_ASSERT -Werror=pointer-arith -DHAVE_CONFIG_H=1 -DHWY_SHARED_DEFINE -pthread -MD -MQ libvips/vips-heif.dylib.p/foreign_heifload.c.o -MF libvips/vips-heif.dylib.p/foreign_heifload.c.o.d -o libvips/vips-heif.dylib.p/foreign_heifload.c.o -c ../libvips/foreign/heifload.c
../libvips/foreign/heifload.c:1201:29: error: incompatible function pointer types assigning to 'int64_t (*)(void *)' (aka 'long long (*)(void *)') from 'gint64 (void *)' (aka 'long (void *)') [-Wincompatible-function-pointer-types]
        heif->reader->get_position = vips_foreign_load_heif_get_position;
                                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libvips/foreign/heifload.c:1203:21: error: incompatible function pointer types assigning to 'int (*)(int64_t, void *)' (aka 'int (*)(long long, void *)') from 'int (gint64, void *)' (aka 'int (long, void *)') [-Wincompatible-function-pointer-types]
        heif->reader->seek = vips_foreign_load_heif_seek;
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libvips/foreign/heifload.c:1204:35: error: incompatible function pointer types assigning to 'enum heif_reader_grow_status (*)(int64_t, void *)' (aka 'enum heif_reader_grow_status (*)(long long, void *)') from 'enum heif_reader_grow_status (gint64, void *)' (aka 'enum heif_reader_grow_status (long, void *)') [-Wincompatible-function-pointer-types]
        heif->reader->wait_for_file_size =
                                         ^
3 errors generated.
```

</details>

relates to https://github.com/Homebrew/homebrew-core/pull/166354

**Comment by lovell** [comment] 2024-03-17 10:11
Not sure it helps directly, but there was an upstream bug in glib relating to the `long` vs `long long` problem that was reported in 2014 and fixed in 2018.

https://bugzilla.gnome.org/show_bug.cgi?id=741488
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/256

**Comment by kleisauke** [comment] 2024-03-17 10:14
It looks like GLib `typedef`s `gint64` as `long`, but this should be `long long` according to the above logs.
```console
$ podman create --arch=arm64 --os=darwin -ti --name dummy ghcr.io/homebrew/core/glib:2.80.0 sh
$ podman export dummy > homebrew-glib.tar
$ podman rm -f dummy
$ tar -xOMf homebrew-glib.tar glib/2.80.0/lib/glib-2.0/include/glibconfig.h | grep 'long gint64'
typedef signed long gint64;
```

The following lines should handle this in GLib:
https://github.com/GNOME/glib/blob/2.80.0/meson.build#L1565-L1600

And it ought to print this during configuring:
```
Checking if "int64_t is long" compiles: NO
Checking if "int64_t is long long" compiles: YES
```

But instead, it prints this:
```
Checking if "int64_t is long" compiles: YES
```
(from the `logs-14-arm64-8211212223` log at https://github.com/Homebrew/homebrew-core/actions/runs/8211212223)

Looking at `build/meson-logs/meson-log.txt` it does this:
```
Running compile:
Working directory:  /private/tmp/glib-20240308-5192-1oamwh/glib-2.80.0/build/meson-private/tmpkslirk7y
Code:
 #if defined(_AIX) && !defined(__GNUC__)
                    #pragma options langlvl=stdc99
                    #endif
                    #pragma GCC diagnostic error "-Wincompatible-pointer-types"
                    #include <stdint.h>
                    #include <stdio.h>
                    int main () {
                      int64_t i1 = 1;
                      long *i2 = &i1;
                      (void) i2;
                      return 1;
                    }
-----------
Command line: `clang /private/tmp/glib-20240308-5192-1oamwh/glib-2.80.0/build/meson-private/tmpkslirk7y/testfile.c -o /private/tmp/glib-20240308-5192-1oamwh/glib-2.80.0/build/meson-private/tmpkslirk7y/output.obj -c -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument -std=gnu99` -> 0
Checking if "int64_t is long" compiles: YES 
```

Perhaps `#pragma GCC diagnostic error "-Wincompatible-pointer-types"` won't work on Xcode 15.3? If that's the issue, this patch might help:
<details>
  <summary>Details</summary>

```diff
--- a/meson.build
+++ b/meson.build
@@ -1571,7 +1571,6 @@ if long_long_size == long_size
   if cc.compiles('''#if defined(_AIX) && !defined(__GNUC__)
                     #pragma options langlvl=stdc99
                     #endif
-                    #pragma GCC diagnostic error "-Wincompatible-pointer-types"
                     #include <stdint.h>
                     #include <stdio.h>
                     int main () {
@@ -1579,12 +1578,13 @@ if long_long_size == long_size
                       long *i2 = &i1;
                       (void) i2;
                       return 1;
-                    }''', name : 'int64_t is long')
+                    }''',
+                    name : 'int64_t is long',
+                    args: '-Werror=incompatible-pointer-types')
     int64_t_typedef = 'long'
   elif cc.compiles('''#if defined(_AIX) && !defined(__GNUC__)
                       #pragma options langlvl=stdc99
                       #endif
-                      #pragma GCC diagnostic error "-Wincompatible-pointer-types"
                       #include <stdint.h>
                       #include <stdio.h>
                       int main () {
@@ -1592,7 +1592,9 @@ if long_long_size == long_size
                         long long *i2 = &i1;
                         (void) i2;
                         return 1;
-                      }''', name : 'int64_t is long long')
+                      }''', 
+                      name : 'int64_t is long long',
+                      args: '-Werror=incompatible-pointer-types')
     int64_t_typedef = 'long long'
   else
     error('Cannot detect int64_t typedef')
```
</details>

(untested)

**Comment by jcupitt** [comment] 2024-03-17 12:42
homebrew builds vips with this extra thingie:

```
  def install
    # workaround for Xcode 15.3, upstream bug report: https://github.com/libvips/libvips/issues/3901
    ENV.append_to_cflags "-Wno-incompatible-function-pointer-types" if DevelopmentTools.clang_build_version >= 1500

    # mozjpeg needs to appear before libjpeg, otherwise it's not used
    ENV.prepend_path "PKG_CONFIG_PATH", Formula["mozjpeg"].opt_lib/"pkgconfig"

    system "meson", "setup", "build", *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"

```

So maybe just set `-Wno-incompatible-function-pointer-types`?

**Comment by jcupitt** [comment] 2024-03-17 12:44
Oh haha wait, that's this bug report! Anyway, it seems to work.

**Comment by kleisauke** [comment] 2024-03-17 18:02
I did a test with commit b4dbd5262daeeaca23d71f7b4576636ab147447c that tries to run the above mentioned GLib compiler checks checks across all macOS versions supported by GitHub Actions (using either `#pragma GCC diagnostic error "-Wincompatible-pointer-types"` or `-Werror=incompatible-pointer-types`).

The results is that it always detects `int64_t` as `long long`, see:
https://github.com/kleisauke/libvips/actions/runs/8317188011

That is with Xcode 13.2.1, 14.2, 15.0.1 and 15.2 (see commit deedef4bf26c5351222a30da2155fa4f9e321a6e). So, it must be a regression in Xcode 15.3. However, I'm not able to confirm this hypothesis, as GHA currently only supports up to Xcode version 15.2 (and due to lack of access to a real macOS device).

**Comment by alanorth** [comment] 2024-03-19 12:09
I was getting this same error on Arch Linux with clang 17.0.0.6 while trying to install pyvips 2.2.2 via [rye](https://github.com/astral-sh/rye). Setting `CFLAGS="-Wno-incompatible-function-pointer-types"` in my environment first allowed it to succeed.

**Comment by kleisauke** [comment] 2024-03-19 13:35
@alanorth Did you mean these Clang errors while installing pyvips?
```
build/temp.linux-x86_64-cpython-312/_libvips.c:6208:27: error: incompatible function pointer types passing 'void (*)(void *)' to parameter of type 'VipsCallbackFn' (aka 'int (*)(void *, void *)') [-Wincompatible-function-pointer-types]
 6208 |   vips_value_set_blob(x0, x1, x2, x3);
      |                           ^~
/usr/include/vips/type.h:275:17: note: passing argument to parameter 'free_fn' here
  275 |         VipsCallbackFn free_fn, const void *data, size_t length);
      |                        ^
build/temp.linux-x86_64-cpython-312/_libvips.c:6256:29: error: incompatible function pointer types passing 'void (*)(void *)' to parameter of type 'VipsCallbackFn' (aka 'int (*)(void *, void *)') [-Wincompatible-function-pointer-types]
 6256 |   { vips_value_set_blob(x0, x1, x2, x3); }
      |                             ^~
/usr/include/vips/type.h:275:17: note: passing argument to parameter 'free_fn' here
  275 |         VipsCallbackFn free_fn, const void *data, size_t length);
      |                        ^
```

If so, it doesn't relate to this issue. The rationale behind this is explained here: https://github.com/libvips/pyvips/blob/3c927624eda87d8e308b723ecbdd98823b1803cf/pyvips/gvalue.py#L249-L251
(the latest GCC version doesn't have this issue at the time of writing)

**Comment by alanorth** [comment] 2024-03-19 16:10
Hi @kleisauke. That looks like the error I was getting. Now I can't reproduce it, even without `CFLAGS="-Wno-incompatible-function-pointer-types"`.

I was using rye + uv to manage my python virtual environment, and that entire toolchain is very much a work in progress, so I kinda assumed it was something there. I don't want to get this thread off track, but I'm not even sure how it chooses clang versus gcc when installing. Anyway, I can't even reproduce it now.

**Comment by kleisauke** [comment] 2024-03-20 09:49
@alanorth pip caches previously built wheels, and uses that  for subsequent installs for the same package version.
https://pip.pypa.io/en/stable/topics/caching/#locally-built-wheels

You can pass the `--no-cache-dir` option to disable this behavior. For example:
```console
$ CC=clang CFLAGS="-Wno-incompatible-function-pointer-types" pip install --user --no-cache-dir pyvips
```

**Comment by kleisauke** [comment] 2024-03-22 10:23
It looks like this will be fixed via PR https://github.com/Homebrew/homebrew-core/pull/166473.

**Comment by kleisauke** [comment] 2024-03-23 11:10
PR https://github.com/Homebrew/homebrew-core/pull/166473 is now landed. `-Wno-incompatible-function-pointer-types` workaround will be removed with PR https://github.com/Homebrew/homebrew-core/pull/166974.

I'll close.

**Closed by kleisauke** 2024-03-23 11:10 UTC
