### ISSUE TITLE
Copy avif to avif loses hdr

### ISSUE THREAD

**Issue by Hanmo123** [libvips/libvips#4212] opened 2024-10-21 14:02 UTC
## Bug report

**Describe the bug**

I got an image(hdr, avif format, 10bit, bt2020) from Adobe Lightroom Classic, and i want to use `vips copy a.avif b.avif` to lower the filesize, but actually the result is not similar with the input.

Adobe Lightroom Classic export settings:
![QQ_1729518681383](https://github.com/user-attachments/assets/8f6dbbe4-d36c-4634-8913-98af9fff0522)

input vs output(as this is a sdr screenshot, so input looks like overexposure)
![QQ_1729518827809](https://github.com/user-attachments/assets/78c33cce-906a-4798-b784-de84dedf1943)

**To Reproduce**

```
libvips copy a.avif b.avif
```

**Expected behavior**

Output should be a hdr image.

**Actual behavior**

The color of output is strange.
I guess libvips did not recognize input as an hdr image.

**Environment**
(please complete the following information)
 - OS: Ubuntu20.04
 - Vips: 8.15.5

**Additional context**

Sample hdr image:
[_DSC0286.avif.zip](https://github.com/user-attachments/files/17462011/_DSC0286.avif.zip)

By the way, if i copy a hdr png image to avif, the result is correct, a sample as well:
https://drive.google.com/file/d/1Xliy869ucGpdgpFugxBhA_1i4UTwnpeQ/view?usp=sharing

**Comment by jcupitt** [comment] 2024-10-22 01:21
Hello @Hanmo123, I think this is a duplicate of #3912, I'll close.

**Comment by jcupitt** [comment] 2024-10-22 01:22
(but thank you very much for the useful example files and screenshots)

**Closed by jcupitt** 2024-10-22 01:21 UTC
Labels: enhancement
