### ISSUE TITLE
About cmyk color image

### ISSUE THREAD

**Issue by jishi92** [libvips/libvips#3159] opened 2022-11-14 14:00 UTC
## Questions, enhancements, tips, etc.

I resize/thumbnail this jpeg image and find the result color is changed.
However, it‘s not changed when imagick is used.
So is it a bug or should I change some parameter?
## Bug report

origin:  
![cmyk-test](https://user-images.githubusercontent.com/22196414/201678606-8e23e44e-6051-4ab2-8759-1add4156ee17.jpeg)

after thumbnail=400x400:  

![cmyk400x400](https://user-images.githubusercontent.com/22196414/201678969-d86d9024-5e19-467f-b248-45551ac1e4a8.jpeg)

**Environment**
OS: centos-8.4, MacOS 12.4
Vips: vips-8.12.1

**Comment by jcupitt** [comment] 2022-11-14 14:49
Hello @jishi92,

There was a bug in vipsthumbnail when used with non-sRGB images and an export profile. If you update to the current stable version (8.13.3) it should be fixed.

I see:

```
$ vipsthumbnail cmyk6.jpeg --size 400
```

To make:

![tn_cmyk6](https://user-images.githubusercontent.com/580843/201690383-3a47fe74-1c06-4dc0-bd5b-f4746cdf912d.jpg)

**Comment by romanzks** [comment] 2022-11-14 15:05
I have a bug reproduced in the version 8.13.3 even without resizing
```
vipsthumbnail input.jpeg --size 4488 -o output.jpeg
```
But interestingly, when using Linear light, the bug is not reproduced
```
vipsthumbnail input.jpeg --size 4488 --linear -o output.jpeg
```
I think this issues is related to https://github.com/libvips/libvips/issues/3150

**Comment by kleisauke** [comment] 2022-11-14 15:14
Perhaps issue https://github.com/libvips/php-vips/issues/138 is also related here? The linked commit in that issue was reverted with PR #3027. Processing in linear space (i.e. `icc_import` on the begin, `icc_export` on the end) would indeed fix that.

**Comment by jishi92** [comment] 2022-11-16 12:29
Hey @jcupitt @romanzks @kleisauke ,
thanks for your answers. I probably understand.
So I should set `icc_export = 'cmyk' ` will solve my question ?
By the way,I don't know what's the meaning of `--linear` in @romanzks 's case.

**Comment by romanzks** [comment] 2022-11-16 12:36
@jishi92 regarding linear light https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking#linear-light

I don't think that icc_export = 'cmyk' is solution. If it works in one case, in not means that will work with other images.

**Comment by jcupitt** [comment] 2022-11-16 12:50
Yes, there's a bug here. I'll try to look into this later in the week.

**Comment by romanzks** [comment] 2022-12-08 18:13
While the issue is being resolved, I suggest considering a temporary solution using a temporary file. This solution has slower performance and a slight reduction in image quality due to the double conversion, but the colors are not affected.

```
vips icc_transform input.jpg temp.jpg[Q=100,strip] sRGB && \
vipsthumbnail temp.jpg --size 400x400 -o output.jpg && \
rm temp.jpg
```

If you're using the PHP binding for libvips, I'd suggest looking at a more productive temporary solution I've developed. For some reason, in some cases conversions are up to 3x faster than when using the Vips\Image::thumbnail() function.

```php
$image = Vips\Image::newFromFile('input.jpg');
$image = $image->icc_transform(Vips\Interpretation::SRGB);
$image = Vips\Image::newFromMemory(
    $image->writeToMemory(),
    $image->width,
    $image->height,
    $image->bands,
    $image->format
);
$image = $image->thumbnail_image(400);
$image->writeToFile('output.jpg', ['strip' => true]);
```

**Comment by kleisauke** [comment] 2022-12-08 18:34
@romanzks I'm not sure if that PHP workaround is desirable in terms of performance, since you are using `thumbnail_image()` (which doesn't support any of the shrink-on-load tricks). Writing to memory and then loading again shouldn't be necessary either. The CLI workaround uses an intermediate JPEG image, so I can't recommend that either in terms of image quality preservation (as you noticed).

I think processing in linear space is the only workaround for now (as mentioned earlier), although it doesn't support shrink-on-load either.

@jcupitt Let me know if you need any help in investigating this and the other linked issue.

**Comment by kleisauke** [comment] 2022-12-08 18:37
@romanzks Sorry, I just noticed that you're the same reporter as https://github.com/libvips/php-vips/issues/169, so processing in linear space is probably not a workaround for you.

**Comment by romanzks** [comment] 2022-12-08 21:18
@kleisauke You're right, I've done more thorough testing, the workarounds are definitely slower (as they should be).
However, as for me, the option with writing and reading from memory makes sense. This is much faster than the option to import and export ICC profiles. And the larger the file size, the bigger the difference. Here are two code examples. As a result of each, we get an image without changing the color. For my tests, I used the first image from this topic.

```php
# it takes 41.83 seconds
$image = Vips\Image::newFromFile('input.jpg');
$image = $image->icc_transform(Vips\Interpretation::SRGB);
$image = $image->icc_import();
$image = $image->thumbnail_image(400);
$image = $image->icc_export();
$image->writeToFile('output.jpg', ['Q' => 90, 'strip' => true]);
```

```php
# it takes 1.41 seconds
$image = Vips\Image::newFromFile('input.jpg');
$image = $image->icc_transform(Vips\Interpretation::SRGB);
$image = Vips\Image::newFromMemory(
    $image->writeToMemory(), $image->width, $image->height, $image->bands, $image->format
);
$image = $image->thumbnail_image(400);
$image->writeToFile('output.jpg', ['Q' => 90, 'strip' => true]);
```

_I apologize if the discussion of PHP is not appropriate here.
But I believe any reasoning on this topic can be useful for resolving the issue._

**Comment by kleisauke** [comment] 2022-12-09 11:14
@romanzks No worries, this problem has yet to be investigated and we need to verify whether it is related to the previously mentioned issues (AFAIK).

Which libvips version was that tested with? It sounds like a similar issue that was resolved with commit https://github.com/libvips/libvips/commit/55723a980fdb9cf4b0180881dd6cf10dadb0731e, feel free to open a separate issue for that (if it is reproducible on the latest libvips version).

Also, instead of that `writeToMemory()`/`newFromMemory()` construction, I think you could use `copyMemory()` instead, for example:
```php
$image = $image->copyMemory();
```

(I can't verify this performance degradation at the moment, as I need to reinstate my PHP environment 😅)

**Comment by kleisauke** [comment] 2023-03-01 10:18
> You get a different result with `colourspace` and `icc_transform`, which is curious.
> 
> ```
> $ vips colourspace cmyk6.jpeg x1.jpg srgb
> $ vips icc_transform cmyk6.jpeg x2.jpg srgb
> ```

You'll see similar images if you swap that last command with:
```console
$ vips icc_transform cmyk6.jpeg x2.jpg srgb --input-profile=cmyk
```

Perhaps `colourspace` is using the built-in CMYK profile instead of the embedded ICC profile?

FWIW, I tried to simplify `icc_transform.c` with commit https://github.com/kleisauke/libvips/commit/850fd16b819404cb45d000ebcdfda056bb153b2d, but that seems to cause a test failure in `TestColour.test_cmyk`.

**Comment by romanzks** [comment] 2023-03-01 10:32
@kleisauke Thanks for working on this issue!

**Comment by kleisauke** [comment] 2023-03-01 16:49
It appears that the embedded ICC profile was ignored due to a previous colourspace conversion, making the profile incompatible with the image. For example, on the master branch I see:
```console
$ vipsthumbnail cmyk6.jpeg -s 3543x4488 -i cmyk -e srgb -o x.jpg

(vipsthumbnail:62994): VIPS-WARNING **: 17:47:34.427: profile incompatible with image

(vipsthumbnail:62994): VIPS-WARNING **: 17:47:34.427: profile incompatible with image
```

I just opened PR #3369 for this.

**Closed** 2023-03-17 19:05 UTC
Labels: bug

**Comment by zhifengzhuang** [comment] 2023-05-03 07:34
> hi @jcupitt ,I use vips-8.14.2 on mac.However,I still get different result with vips icc_transform and vips colourspace.
`vips colourspace cmyk.jpeg cmyk-colourspace.jpeg srgb`
![image](https://user-images.githubusercontent.com/13492988/235856191-a7d37255-08dc-4f00-a44b-da86202f2fb8.png)
`vips icc_transform cmyk.jpeg cmyk-icc.jpeg srgb`
![image](https://user-images.githubusercontent.com/13492988/235856254-e688c453-ec4f-43b8-8c4d-a48af0efdf53.png)

**Comment by kleisauke** [comment] 2023-05-03 08:23
> I still get different result with vips icc_transform and vips colourspace.
> ```console
> vips colourspace cmyk.jpeg cmyk-colourspace.jpeg srgb
> vips icc_transform cmyk.jpeg cmyk-icc.jpeg srgb
> ```

@zhifengzhuang This is expected as [`vips_colourspace()`](https://www.libvips.org/API/current/libvips-colour.html#vips-colourspace) only looks at the [interpretation field](https://www.libvips.org/API/current/VipsImage.html#VipsImage--interpretation), it will ignore any embedded ICC profiles.

> The latest update fixed some of the bugs with color rendering after transformation, but it looks like some still remain.

@romanzks Please open a new issue with sample images, allowing someone else to reproduce.

**Comment by romanzks** [comment] 2023-05-03 11:25
The issue https://github.com/libvips/libvips/issues/3479 is open

**Comment by kleisauke** [comment] 2023-05-07 10:07
I just opened PR #3483 to ensure CMYK conversion will use the embedded ICC profile, if available.

**Comment by jcupitt** [comment] 2025-03-05 12:30
@silva96 please open a new issue for a new question.

Are these screenshots? They don't look quite the same. You'll need to upload the true original image and the true failure before I can investigate anything.
