### ISSUE TITLE
SVS image convert to jpg

### ISSUE THREAD

**Issue by ricklina90** [libvips/libvips#1401] opened 2019-08-21 02:48 UTC
Hello,
          With libvips 8.8.1 , I'm trying to convert some of svs file to jpg. I meet some problems.  Some of svs file aren't successfully converting to jpg.
This issue wasn't there with previous version 8.7.4.

svs image source link: http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs
command: vips openslideload --level 2 cmu-1.svs test.jpg

8.7.4
![8 7 4](https://user-images.githubusercontent.com/53546552/63398190-5dd7a080-c3ff-11e9-81ec-09d0de9e5589.jpg)

8.8.1
![8 8 1](https://user-images.githubusercontent.com/53546552/63398210-721b9d80-c3ff-11e9-8adf-a2bab5031fb4.jpg)

Thanks for your attention,
Rick

**Comment by jcupitt** [comment] 2019-08-21 09:38
Hello Rick, I tried with 8.9 and it works fine, I'll have a go with 8.8 as well.

**Comment by jcupitt** [comment] 2019-08-21 09:42
Yes, 8.8 works too. 

Could some other change in your system be responsible? Have you changed your openjpeg version, for example?

**Comment by ricklina90** [comment] 2019-08-22 03:51
I trying to test on Windows 10 in 1809 and 1903 the problem still exist. Here is attach file on lib

vips 8.7.4 and 8.8.1 operation.

[8.7.4.mp4.zip](https://github.com/libvips/libvips/files/3528174/8.7.4.mp4.zip)
[8.8.1.mp4.zip](https://github.com/libvips/libvips/files/3528176/8.8.1.mp4.zip)

Thanks for your attention,
Rick

**Comment by jcupitt** [comment] 2019-08-22 07:16
Oh, I had no idea you were using Windows.

Yes, the Windows 8.8.1 binary might be using a bad version of openjpeg. I'll check.

**Comment by ricklina90** [comment] 2019-08-22 07:43
Thanks for the quick reply. Wish hear a good news in near future.

**Comment by kleisauke** [comment] 2019-08-22 08:23
I could reproduce this with the Windows binaries. The Windows 8.8.1 binary is using OpenJPEG 2.3.1.

I'll try to include commit https://github.com/openslide/openslide/commit/fa3e3355ec48924dafc0ff3894ab448c6c6a9ef0 and https://github.com/openslide/openslide/commit/64017b5d8dcbf091e55bda59b88d9bb7f87013ad to see if that fixes it. If that doesn't work, it might make sense to downgrade OpenJPEG to 2.3.0 (but I'd rather avoid that).

**Comment by kleisauke** [comment] 2019-08-22 10:05
This is also reproducible on Linux (tested on Fedora 30 with libvips 8.8.1):
```bash
wget http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs
vips copy JP2K-33003-1.svs[level=2] x.jpg
```
```bash
wget http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs
vips copy CMU-1.svs[level=2] x.jpg
```

It seems that it only happens for the scaled-down versions of the high-resolution image (level > 0).

**Comment by jcupitt** [comment] 2019-08-22 10:25
It's working on Ubuntu 19.04 with openjpeg 2.3.0-2 and libvips 8.8 and 8.9 (git master).

Did you manage to get a working win version with those openslide patches?

**Comment by kleisauke** [comment] 2019-08-22 11:39
I managed to get a buildable OpenSlide version with those patches, but it produces the same output. I also tried to downgrade OpenJPEG to 2.3.0 and 2.1.1 (within the Windows builds), but it still has the wrong output.

To make it easier to reproduce, you can try this Dockerfile:

```Dockerfile
FROM fedora:30

RUN dnf install -y https://rpms.remirepo.net/fedora/remi-release-30.rpm \
    && dnf --enablerepo=remi install -y vips-tools

RUN curl -OL http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs \
    && vips copy JP2K-33003-1.svs[level=2] x.jpg
```

```bash
docker build . -t issue-1401
docker create -ti --name dummy issue-1401 bash
docker cp dummy:x.jpg .
docker rm -fv dummy
```

**Comment by jcupitt** [comment] 2019-08-22 11:45
Huh how weird, it must be some other difference then. 

I'll have a look.

**Comment by kleisauke** [comment] 2019-08-22 12:17
This looks likes a dependency or OpenSlide issue:

```Dockerfile
FROM fedora:30

RUN dnf install -y openslide-tools

RUN curl -OL http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs \
    && openslide-write-png JP2K-33003-1.svs 0 0 2 1921 2187 x.png
```

Output:
![x](https://user-images.githubusercontent.com/12746591/63513723-41af2e80-c4e7-11e9-8bc5-7c6fbfd34ee6.png)

**Comment by jcupitt** [comment] 2019-08-22 14:15
Could it perhaps be a libtiff issue? Aperios (SVS) is more or less TIFF with jp2k compression, and openslide uses libtiff to fetch tiles.

**Comment by jcupitt** [comment] 2019-08-22 14:25
I tried building openslide with libtiff 4.0.10-4 (ubuntu 19.04 package) and 4.0.10 (unpatched 4.0.10 from libtiff git) and both worked. This is with openjpeg 2.3.0.

**Comment by kleisauke** [comment] 2019-08-23 09:53
This has also been reported to OpenSlide, see: https://github.com/openslide/openslide/issues/278.

Could it perhaps be a GLib issue? I see a lot of deprecation warnings while compiling, see [the compile log](https://gist.github.com/kleisauke/8512ff0e1eb90b927172d64c96d19063). I guess the dependency that causes these issues is listed here: https://github.com/libvips/build-win64/pull/26 (libtiff is not listed). I'll try to downgrade the OpenSlide dependencies one at a time to see if that fixes it.

**Comment by kleisauke** [comment] 2019-08-23 11:41
I tested GLib 2.56.1 (the one used by the Windows builds of OpenSlide) and GLib 2.59.0 (the last release with autotools support) without luck. I'll try to recompile all dependencies with an older version of GCC and without optimization flags.

**Comment by jcupitt** [comment] 2019-08-23 11:52
It's working on Ubuntu 19.04 with gcc 8.3.0, fwiw.

**Comment by kleisauke** [comment] 2019-08-23 14:17
Gotcha! Pixman seems to be the culprit. I downgraded it to 0.36.0 (from 0.38.4) and didn't see any issues anymore. Cairo uses the low-level Pixman library for pixel manipulation and OpenSlide uses Cairo to read regions from whole-slide images:
https://github.com/openslide/openslide/blob/f55a3bf34053ba10b32b0d902a36105fbb3ac205/src/openslide.c#L482

Applying this commit on top of Pixman 0.38.4 solves the problems:
https://gitlab.freedesktop.org/pixman/pixman/commit/8256c235d9b3854d039242356905eca854a890ba

Ubuntu 19.04 uses Pixman 0.36.0, whereas Fedora 30, Homebrew (macOS) and the Windows builds of libvips uses Pixman 0.38.4.

**Comment by jcupitt** [comment] 2019-08-23 14:22
Wow, well done!

**Comment by kleisauke** [comment] 2019-08-23 16:11
A pull request has been made to fix this issue within the Windows builds: https://github.com/libvips/build-win64/pull/31. 

This patch can be removed if a new version of Pixman is available.

**Comment by ricklina90** [comment] 2019-08-27 01:29
Thank you all. I need libvips Windows binaries to test my SVS file.

Thanks for your attention,
Rick

**Comment by kleisauke** [comment] 2019-08-27 09:35
You can download the libvips Windows binaries (`-all` distribution) built from commit libvips/build-win64@5a13fd2 here:
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-all-8.8.1-5a13fd2.zip

This will also be resolved in the Windows binaries of libvips 8.8.2.

**Comment by ricklina90** [comment] 2019-08-27 10:07
It works fine. Thanks again! Very appreciated :)

**Comment by jcupitt** [comment] 2019-09-02 09:23
8.8.2 is out now and should also have this fix.

**Closed by jcupitt** 2019-09-02 09:23 UTC
Labels: question

**Comment by EKami** [comment] 2019-09-02 19:04
Oh my gosh, thank you so much for this, 2 of my machines were affected by this bug and I couldn't find a solution for this for months! I'm gonna try your solution, thanks all!

**Comment by EKami** [comment] 2019-12-18 04:14
Is it possible to have the next versions of pyvips directly shipping with the right static lib of pixman instead of relying on the dynamic lib? I'm having headaches with this bug each time I install pyvips on a new machine either with conda or when I compile libvips from source :( . Thanks!

**Comment by jcupitt** [comment] 2019-12-18 09:27
Sorry, it's a packaging issue, you need to pester the conda maintainers to fix the bug.

**Comment by EKami** [comment] 2019-12-18 09:45
I guess I'll have to rely on the pip package then, thanks @jcupitt

**Comment by YoniSchirris** [comment] 2020-04-21 10:11
@EKami What are the exact steps that you took to fix this? I don't use libvips, but use opencv and openslide, which in its turn use cario and pixman, where there's a dependency loop that eventually gives me pixman 0.38.0 with the bug. Downgrading to 0.36.0 doesn't work as I don't know exactly how to solve the dependencies, so I'd like to try upgrading to the fixed pixman, but don't understand how to do this.

**Comment by jcupitt** [comment] 2020-04-21 10:19
It looks like pixman 0.40 was (finally!!) released three days ago, so hopefully this very annoying bug will now get patched away.

Homebrew has already been updated, conda should follow soon.

**Comment by EKami** [comment] 2020-04-21 10:28
@jcupitt Awesome news!

@YoniSchirris I didn't bother waiting for a new release of pixman. What I did was removing all instances of pixman on my machine (using `ldconfig -p | grep libpixman` and removing it in `anaconda3/lib/` and `anaconda/envs/myenv/lib/`), then I just created my own version of pixman with the patch [here](https://github.com/EKami/pixman) which I then compiled and installed on my system.

Since 0.40 is now released you may want to use this version instead of mine :)

**Comment by YoniSchirris** [comment] 2020-04-21 10:46
@jcupitt I now have v0.40.0 installed with brew, but conda is still pointing to v0.38.0. So I guess the best thing to do is wait until I can install 0.40 with conda, and then hope there's no dependency rabbit hole then. 

@EKami Since I have to run this on a remote server where I don't have complete write access, I'm afraid I have to wait for conda indeed. 

I'll update here to let you know if it's worked

**Comment by jcupitt** [comment] 2020-04-21 10:56
@YoniSchirris yes, conda has its own packaging system and exists in its own private world. You'll have to wait for a conda update, or get your hands very, very dirty (as @EKami did heh).

If you stay outside conda it might be simpler -- you can build the stack to a prefix in your home area and run from that. I've used docker for deployment as well, I don't know if that's an option.

**Comment by YoniSchirris** [comment] 2020-04-21 11:51
@jcupitt A docker container could work. What would you then suggest? I need openslide, openslide-python, opencv, py-opencv, large-image, large-image-source-openslide, marshmallow, pillow, and a bunch of other image dependencies. 
- create ubuntu 18.04 image (I think this has the best support for pixman overall)
- install the v0.4.0 lib
- install all the above python libraries with pip?

I'm not experienced with how such dependencies on non-python modules work, so apologies for any unclear questions.

**Comment by jcupitt** [comment] 2020-04-21 11:58
I think you can use 19.04 as a base (it comes with a working pixman).

I would write a dockerfile that built your stack to `/usr/local` (in the container, obvs.), push that to dockerhub, then to deploy just execute `docker run --rm -t my-username/my-container:latest ...` wtc. on the server.

If the container image is too big, you can trim it down by removing the build parts, but that might not be necessary, it depends on your requirements.
